README.md
Add a link to the documentation in the logo of the README
=> docs: add link to documentation

packages/fscomponents/src/components/AddToCart.tsx
Swatches `defaultValue` is defined as an optional so `undefined` should be used instead of `null` to indicate no `defaultValue`.
=> fix(fscomponents): use undefined as Swatches defaultValue

packages/fsshopify/src/__tests__/ShopifyDataSource.test.ts
Resolves build issue in https://github.com/brandingbrand/flagship/pull/3
The new version of react-native-payments introduced by Greenkeeper uses ReactNative.requireNativeComponent to import native UI widgets. Because the ShopifyDataSource test mocks react-native, we need to mock this method as well to prevent the test from erroring.
=> fix(fsshopify): fix shopifydatasource test

packages/pirateship/src/lib/commerceCloudMiddleware.ts
The html in the product descriptions coming from Demandware has spacing between <li> elements which is rendered as such by react-native-htmlview. This updates the Demandware middleware to remove spaces before <li elements in product descriptions.
=> fix(pirateship): clean up demandware product descriptions

.travis.yml
greenkeeper-lockfile version 2 adds support for monorepos
=> chore: update to greenkeeper-lockfile 2

packages/fscomponents/src/components/ProductItem/components/ProductItemImage.tsx
In ProductItemImage.tsx event was being referenced inside the scope of the callback so it wasn't set. Moved the definition above the callback to avoid this issue.
=> fix(pirateship): fix undefined variable error on product grid

.travis.yml, package.json, yarn.lock
Attempt to fix CI issues with greenkeeper-lockfile by following the suggestion of adding it as a devDependency instead of attempting to add it as a global to yarn.
=> fix: attempt to fix greenkeeper-lockfile ci issues

package.json, yarn.lock
greenkeer-lockfile is erring for Flagship CI but doesn't have any error trapping/logging so all we see is "command failed". This wraps all the exec statements in try/catch blocks that console logs stderr to hopefully get more information.
=> chore: update greenkeeper-lockfile to brandingbrand fork

packages/flagship/src/lib/link.ts
There appears to be a bug in how node-suspect, the library we're using to interact with the command line during the init process, handles output buffers. The symptom is hanging when running init while using Node 8. For whatever reason, forcing react-native link into --verbose mode resolves this issue.
This also removes an extraneous sendEof() command that's not necessary when CodePush is not enabled for a project.
=> fix(flagship): updates/fixes to init script

packages/fsapp/src/components/screenWrapper.web.tsx
The first passed property always included the ? query string delimiter (eg. `?categoryId`)
=> fix(fsapp): Fix parsing of query string passprops

packages/fsproductindex/src/components/ProductIndexProvider.tsx
Since the requestReviews method now alters the component's state rather
than triggering an update that results in new props being passed in, the
props/state commerceData in getDerivedStateFromProps were never equal.
This caused the subsequent componentDidUpdate call to always request a
new set of reviews.
=> fix(fsproductindex): Fix infinite loop of requesting reviews

packages/pirateship/src/components/PSProductDetail.tsx, packages/pirateship/src/components/PSProductIndex.tsx, packages/pirateship/src/components/PSRecentlyViewedCarousel.tsx, packages/pirateship/src/lib/commonTypes.ts, packages/pirateship/src/lib/shortcuts.ts, packages/pirateship/src/screens/Development.tsx
Importing react-native-navigation breaks compiliation for web. We're
only using it for its type definitions in these places, so we can use
the new typescript type imports to get around this.
=> refactor(pirateship): Use TS 2.9 type imports for RN Navigation

packages/pirateship/src/components/PSProductDetail.tsx, packages/pirateship/src/screens/ProductDetailReviews.tsx
PassProps get serialized into query string parameters on web, so passing
the review data source (a class/function) into the new screen does not
work on web. Also, removed some debugging code that was accidentally
left in.
=> fix(pirateship): Don't pass review datasource to screen as a prop

packages/fsshopify/src/customTypes.ts, packages/fsshopify/src/mixins/ShopifyCartDataSource.ts, packages/fsshopify/src/util/DataSourceBase.ts, packages/fsshopify/src/util/react-native-payments.ts, packages/fsshopify/src/util/react-native-payments.web.ts
- Mock out react-native-payments
- Don't auto-register Google Pay Shipping Options Modal (should be
handled in the project). The screen name of the modal is to be passed in
as a config option.
=> fix(fsshopify): Make fsshopify work on web

packages/pirateship/src/screens/Cart.tsx
- used existing grays.eight, the variable set to palette.secondary: hex '#343434'
=> fix(pirateship): fixes empty cart title color to secondary dark gray

packages/pirateship/src/screens/Cart.tsx
- set to palette.secondary, which is grays.eight
=> fix(pirateship): fixes empty cart text color to secondary dark gray

package.json, yarn.lock
There was a bug in react-native-web that prevented scroll events from
propagating through multiple scrollviews (or elements that use
scrollview internally like flatlist).
=> fix(pirateship): Fix scrolling on web

packages/pirateship/scripts/buildWebDemo.sh
Needed a trailing slash at the end of the public-path variable so paths would be concatenated
correctly
=> fix(pirateship): Fix demo web app build script

packages/pirateship/src/screens/Cart.tsx
1. In PirateShip, launch web
2. Navigate to the Cart page without any items in cart
3. Click the Continue Shopping button
4. Verify that you return to the Shop screen
=> fix(pirateship): fix continue shopping button for web

packages/fsapp/src/lib/env-switcher.web.ts, packages/fsweb/webpack.config.js, packages/pirateship/scripts/buildWebDemo.sh
Can now use a couple new env options with webpack
--env.enableDev to control if __DEV__ is set
--env.defaultEnvName to specify an environment when using webpack
=> feat: Add flags for setting env/dev when using webpack

packages/fsapp/src/components/DevMenu.web.tsx
Instead of navigating to `/` after switching environments, only reload the current page. This avoids the assumption that the app will be served from the root directory.
=> fix(fsapp): Don't navigate when switching envs

packages/fscomponents/src/components/Accordion.tsx, packages/fscomponents/src/components/__stories__/Accordion.story.tsx
BREAKING CHANGE: iconFormat property has new option name “arrow” which corresponds to what was previously “image”. “image” is now the property name which designates custom disclosure icon option. default is still “plusminus”.
also added stories in storybook to show different options
=> feat(fscomponents): add custom disclosure icon option to accordion

packages/flagship/ios/FLAGSHIP.xcodeproj/project.pbxproj, packages/flagship/ios/FLAGSHIP/GoogleService-Info.plist
This registers an empty GoogleService-Info.plist with the Flagship Xcode Project. This will be modified by projects implementing Firebase.
=> feat(flagship): add firebase plist placeholder to xcode project

packages/flagship/src/lib/modules/react-native-firebase.ts, packages/flagship/src/lib/path.ts, packages/flagship/src/types.ts
This adds a script to perform the necessary actions to install base Firebase and Firebase Analytics on iOS and Android. As with the other module scripts, it'll be run only when a particular dependency exists on a project, in this case react-native-firebase.
Requires the following to be added to the end project's config:
```
{
firebase: {
ios: {
googleServicesPlistFile: '<path to GoogleService-Info.plist>'
},
android: {
googleServicesJsonFile: '<path to google-services.json>'
}
}
```
=> feat(flagship): add module install script for react-native-firebase

packages/flagship/src/lib/modules/react-native-firebase.ts
Flagship init is used as part of our CI process on non-Mac machines. The Pod helper checks for the correct environment before running pod install. This replaces manual pod install with the helper for the Firebase module.
=> fix(flagship): use pod helper to avoid ci errors in firebase

packages/fscomponents/src/components/Grid.tsx
closes issue #178 
width still configurable by the user through rowSeparatorStyle & columnSeparatorStyle props
=> fix(fscomponents): make grid column & row separators visible

packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/MainApplication.java, packages/pirateship/package.json, yarn.lock
https://github.com/brandingbrand/flagship/pull/186 is not fixed if `react-native-navigation@^1.1.469` is being used anywhere. PirateShip appears to be the only place where it was being used so this should fix it. I also added the `@Override` annotation back in to `flagship/MainApplication.java` and it shouldn't cause any problems now.
=> fix(pirateship): remove old react-native-navigation version

packages/fscodestyle/package.json, packages/fscodestyle/tslint.json, packages/fsi18n/package.json, packages/fsmockdatasources/package.json, yarn.lock
- Update tslint to 5.11.0
- Update tslint-eslint-rules to 5.4.0
This adds support for TypeScript 3.0, which means the linter now picks up on type imports. Since these are directly exported in the `.d.ts` files they should be included as a dependency.
This change also removes the `no-unused-variable` rule which was deprecated in tslint 5.11.0.
=> chore: update tslint to 5.11.0

packages/flagship/android/app/build.gradle, packages/flagship/android/build.gradle, packages/flagship/package.json, packages/fstestproject/package.json, packages/pirateship/package.json, yarn.lock
The FSI18n package makes use of some newer JS features that do not exist in the default JSC included with React Native.
@DanielClayton can you take a quick look over the Android changes?
=> feat: Update Android JavaScriptCore

packages/fsapp/package.json, packages/fsshopify/package.json, packages/pirateship/package.json, yarn.lock
* Fix react-native-navigation version
From https://github.com/wix/react-native-navigation, "Version 1.1.483 supports react-native >= 0.48 up to react-native 0.56 Version 1.1.484 supports react-native >= 0.57."
=> fix: Fix react-native-navigation version

packages/flagship/src/lib/modules/react-native-camera.ts
Adds a module to upgrade the gradle version when using react-native-camera
Fixes #213
=> fix(flagship): Add module support for react-native-camera

packages/fscomponents/src/components/SearchBar.tsx
Adds an optional right icon button to the search bar. Can be used to implement addtional search
functionality, such as a bar code scanner.
Example:
=> feat(fscomponents): Add right icon/button support to search bar

packages/flagship/src/lib/modules/react-native-camera.ts
Using Android Asset Packaging Tool 2 causes issues with some of our assets.
=> fix(flagship): Disable AAPT2 for react-native-camera module

packages/flagship/src/lib/modules/react-native-firebase.ts
react-native-firebase defaults to version 16 of Firebase Android dependencies, while react-native-push-notifications defaults to version 17 because there's no version 16 of one of its dependencies, firebase messaging. Android build will fail due to this version mismatch. This disables strict version checking by the Google libraries.
=> fix(pirateship): disable strict version checking for google services

packages/fscomponents/src/components/PromoForm.tsx
The PromoForm component passes all of its props to the SingleLineForm component, so it should
inherit the applicable props
=> fix(fscomponents): Fix PromoForm props

lerna.json
All packages will have identical version numbers so packages with a set version numbers are always known compatible with each other.
=> feat: switch to combined versioned releases

packages/flagship/src/lib/modules/react-native-code-push.ts, packages/flagship/src/types.ts
Previously flagship was using private branding brand app center token for authentication.
This solution requires you to self manage app center token, which allows teams outside Branding Brand organization to use code push.
=> fix: Require project to provide app center token

packages/flagship/android/build.gradle
Fixed per this issue when android build failed:
https://forum.ionicframework.com/t/could-not-find-play-services-basement-aar-com-google-android-gms-play-services-basement/145529
moves jcenter() to end of:
```
allprojects {
repositories {
}
}
```
in android/build.bgradle
=> fix(flagship): runs jscenter() last in build.gradle/repos

lerna.json
Per the documentation this will publish all packages regardless of whether there were changes in each. This is intended behavior as we prefer to keep all package version numbers in sync.
=> chore: set lerna force publish on all packages

.travis.yml, packages/flagship/src/commands/init.ts, packages/flagship/src/lib/modules/react-native-adobe-analytics.ts, packages/flagship/src/lib/modules/react-native-firebase.ts, packages/flagship/src/lib/modules/react-native-leanplum.ts
- Removed duplicate places where pod install was running
- Updated module patch scripts so they run before `react-native link`
- Run `pod install` after `react-native link`
=> fix(flagship): run pod install after react-native link

packages/fscomponents/src/components/ReviewIndicator.tsx
If an itemColor was set, all stars would appear to be full
=> fix(fscomponents): Fix setting ReviewIndicator color and passed props

packages/fscomponents/src/components/ReviewItem.tsx, packages/fscomponents/src/components/ReviewsList.tsx, packages/fscomponents/src/components/ReviewsSummary.tsx
ReviewItem, ReviewList, and ReviewSummary all set the required ReviewIndicator props, so their
reviewIndicatorProps prop should allow a partial set of properties.
=> fix(fscomponents): Allow partial reviewIndicatorProps to be passed

packages/flagship/src/lib/modules/react-native-firebase.ts
Google published a new version of its GoogleAppMeasurement pod, 5.4. This appears to have been compiled using Xcode 10 which is not yet compatible with Flagship.
This change pins the Firebase pod version to 5.12 (the last known good version that we also know is compatible with GoogleAppMeasurement 5.3) and pins GoogleAppMeasurement to 5.3.
=> chore(flagship): pin firebase and googleappmeasurement pods

packages/fsengagement/package.json
@bweissbart We found that if you have prelink in one of the packages, it will hang the init of the app.  Removing it allowed the init process to finish normally.
=> feat(fsengagement): remove prelink react-native-fcm

packages/pirateship/package.json, yarn.lock
fsshopify added react-native-payments as a dependency for end projects. This adds a react-native-payments dependency to pirateship; it has to be pinned to the same version as in fsshopify in order for RN native modules to resolve it properly.
=> fix(pirateship): add missing rn payments dependency

packages/fslocator/package.json
**Ticket:** https://jira.brandingbrand.com/browse/
react-native-maps version in use was throwing an error 'Invariant Violation: Native component for "AIRMap" does not exist'
updating to use https://github.com/brandingbrand/react-native-maps#0.21.0-gradle2 fixes this issue
build a project that includes fslocator
app should not fail during yarn run ios
=> fix(fslocator) update react-native-maps to use BB repo

packages/fsengagement/src/inboxblocks/EventCard.tsx, packages/fsengagement/src/inboxblocks/FeaturedTopCard.tsx
`screen: LayoutBuilder` was mistakenly left in, causing a crash when clicking on an event type.  Needs to be changed to `EngagementComp`.
=> fix(fsengagement): fix crashing when trying to view event item

packages/fsbazaarvoice/src/BazaarvoiceDataSource.ts
`data.Includes.Products` doesn't appear to get set unless there's at least one review for a product.
=> fix(fsbazaarvoice): guard against unset includes in bv response

package.json
The build-web-demo step of Travis is consistently causing a JS heap error. This removes this step so that we aren't blocked on deploying urgent fixes.
Logged this as an issue here: https://github.com/brandingbrand/flagship/issues/331
=> chore: temporarily remove web demo from build:docs

packages/fscomponents/src/components/Form/Form.tsx
On some minor forms on the page, you want to be able to require fields on submit, because they are needed when you submit, but not show error messages on blur about those fields being required, as it can misleadingly indicate that those fields are required to submit the page's main form. A good example of this is when you have a checkout page that has a field to apply a promo code or membership id. These fields aren't required for the functionality of the page's larger form, so they shouldn't indicate that when you click off of them, but they are required for the functionality of that smaller form, so they should indicate that they are when submitting that form.
We may also want to be able to turn off validate on blur for individual fields, but turning it off for the form will likely …
=> feat(fscomponents): Allow turning off validate on blur

packages/fsengagement/src/EngagementService.ts
@bweissbart 
If we first getProfile as an anonymous user, then later login and getProfile again it will simply return your stored profile info without making another request.  This allows us to pass a flag to force the syncing of  the profile (forces request to engagement api to sync username/email with profileId).
=> fix(fsengagement): add flag to enable forced resync

packages/fsengage/src/modules/analytics/providers/AnalyticsProvider.ts, packages/fsengage/src/modules/analytics/providers/adobe/AdobeAnalyticsProvider.ts
Adobe Analytics expects the total price for products, rather than the unit price
=> fix(fsengage): Fix product serialization for Adobe Analytics

packages/fscomponents/src/components/__stories__/CMSBannerCarousel.story.tsx
we need the arrow to be able to toggle through the banners on web
=> fix(fscomponents): default show arrow on cms banner carousel story

packages/fscomponents/src/components/CMSFeedback.tsx
currently, because `MultilineStylesheet` references outdated properties, CMSFeedback component won't render. See example on Storybook:
Deleting this stylesheet allows "Report a Site Issue" button to render, and when you click on it, you now see this:
Still could use some more fined tuned styling, but better is good :)
=> fix(fscomponents): remove outdated stylesheet on cmsfeedback component

packages/fscomponents/src/components/ReviewsSummary.tsx
for an input of ’80’,  review summary was showing ‘8000%%’, now it will show ’80%’
=> fix(fscomponents): fix review summary percent recommend

packages/fscomponents/src/components/__stories__/ImageWithOverlay.story.tsx
In current form, the image with overlay storybook is not clear. It seems like the "Banner Text" may be overlay, but that is incorrect ("banner text" is actually part of example image file), the text overlay is actually a barely visible "overlay" text blob currently invisible in bottom left corner:
This image and text combination makes it clear what is image, what is overlay
=> fix(fscomponents): make clear what is image and what is overlay

packages/flagship/ios/Podfile
The new build system in Xcode 10 is throwing a duplicate "provides" error when archiving a Flagship app. This adds logic to the template Podspec that removes yoga from the project.
We should have someone with iOS expertise review our entire default Podspec to see if we're including unnecessary modules (this seems to be the case from my untrained eyes) but in the meantime this fixes the archive problem.
Solution from this discussion: https://github.com/facebook/react-native/issues/20492#issuecomment-422958184
=> fix(pirateship): ignore yoga in template podspec

packages/flagship/android/app/build.gradle
Updates the android.support dependencies in build.gradle to use supportLibVersion constant which is currently set to 27.1.1.
Note: the upgrade to support lib 27 was dictated by RN: https://github.com/react-native-community/react-native-releases/blob/master/CHANGELOG.md#tooling-updates
=> fix(flagship): pin android.support libs to 27

packages/pirateship/src/components/PSButton.tsx
PSButton as Stateless Function Component, testable throughout Pirateship package.
=> refactor(pirateship): psbutton to sfc

packages/fscomponents/src/components/CartCount.tsx, packages/pirateship/src/screens.tsx, packages/pirateship/src/screens/CartCountSample.tsx, packages/pirateship/src/screens/Development.tsx
Adding react.memo as it started as a PureComponent. Also built a demo screen in Development menu:
=> refactor(fscomponents): cartcount to sfc w memo and demo

packages/fsapp/src/fsapp/FSApp.web.tsx, packages/fsapp/src/fsapp/FSAppBase.tsx, packages/fsapp/src/lib/env-switcher.web.ts, packages/fsapp/src/types/index.ts
Also allows setting serverSide config option to prevent the application from being run and adds a safety check to accessing localStorage.
When running server side, we don't want to run the application, we just want to render it once, so running it eats up resources unnecessarily.
=> fix(fsapp): Expose getApplication functionality for SSR

packages/fsapp/src/components/DevMenu.web.tsx
Going back before reloading makes it reload the page that loaded the environment switcher, rather than the environment switcher itself.
=> fix(fsapp): On web dev menu, go back before refreshing

packages/fsapp/src/components/screenWrapper.web.tsx, packages/fsapp/src/fsapp/FSApp.web.tsx, packages/fsapp/src/types/index.ts
Allows setting devMenuPath in the config to override the path that the dev menu is displayed on web. Also updates the web screen wrapper to more-closely match the native version's functionality and will suppress the link to the dev menu with the same logic used to determine if the screen should be added to the list.
=> fix(fsapp): devMenu path override and web screen wrapper update

packages/fsapp/src/components/DrawerRouter.web.tsx, packages/fsapp/src/components/screenWrapper.tsx, packages/fsapp/src/components/screenWrapper.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/ReviewsList.tsx
IE11 hates its `flex-basis: 0`s. It also does some weird things with rotated arrows, and this removes the thin border line that appears on them in the Multicarousel.
=> fix(fscomponents): Fixes for IE11

packages/fscomponents/src/components/ReviewIndicator.tsx
-removing accessible prop from wrapping view so the component can be skipped in tab order
=> fix(fscomponents): remove accessible prop to stop focus

packages/pirateship/src/components/PSRowHeader.tsx
=> refactor(pirateship): psrowheader to stateless function component

packages/pirateship/src/components/PSHalfModal.tsx, packages/pirateship/src/screens/Development.tsx, packages/pirateship/src/screens/EmailSignUp.tsx
PSHalfModal refactored to stateless functional component and testable in development menu: enter email for promos, etc. results in a half-modal success message. Did not 'memo'-ize given low frequency of props being changed and not worth the extra computational time.
=> refactor(pirateship): pshalfmodal to stateless function component

packages/flagship/ios/FLAGSHIP/AppDelegate.m
Move the variable that leanplum sets for the notification url (“_lpx”)  to the default ios variable “UIApplicationLaunchOptionsURLKey” so that it gets passed to the Linking function of React Native
=> fix(flagship): pass leanplum push url to expected launchOptions value

packages/fsapp/src/components/DrawerRouter.web.tsx, packages/fsapp/src/types/index.ts
The router that we're using for web supports the ability to pass in a location object that overrides the default behavior of using window.location. This allows for the existing web routing system to work with server side rendering as well.
=> feat(fsapp): add ability to pass location into the web router

packages/fscomponents/src/components/Swatches.tsx
Allows setting maxSwatches to 0 or negative to continue showing all swatches even when show less is selected. This also allows specific styling for the container when less or more is selected. This does slightly alter the behavior because the style is applied to a view wrapping just the swatches and not the more/less selection.
=> feat(fscomponents): Custom styling for swatch show more/less

packages/pirateship/src/screens/ActionBarSample.tsx
changed button title colors to 'onPrimary' so now readable (was black on green, now white).
BEFORE: 
AFTER:
=> fix(fscomponents): actionbar sample styles cleaned up

packages/flagship/__tests__/mock_project/android/app/build.gradle, packages/flagship/android/app/build.gradle
This fix allows Android apps to be built and submitted to the store if
the minimum SDK version is >=21. See:
https://github.com/brandingbrand/flagship/issues/266
=> fix(flagship): remove minSdkVersion from Android versionCode

packages/fscomponents/src/components/ModalHalfScreen.tsx, packages/fscomponents/src/types/Store.ts
This add accessibilityLabel, accessibilityTraits (iOS) and accessibilityComponentType (Android) to ModalHalfScreen.
=> feat(fscomponents): add accessibility for modalhalfscreen background

.travis.yml
Lerna publish is failing on Travis with invalid tag names, and my suspicion based on some Github comments is that Lerna is unable to properly read the history because Travis defaults to shallow clones of repos.
This turns of shallow cloning for the deploy stage to attempt to resolve this issue. https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth
=> chore: disable shallow clone for publish stage of ci

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx
In my use case, I am passing state into the `itemsPerPage`. This was causing an issue where `onLayout` was being called before the component received the new `itemsPerPage` prop and wasn't updating `this.state.itemWidth` appropriate, since the only place where that is set is in the `onLayout` function. Setting the new `itemWidth` will allow the user to dynamically update `itemsPerPage` and see their changes propagated without firing `onLayout`.
=> fix(MultiCarousel) update state.itemWidth when props.itemsPerPage changes

packages/fsweb/babel.config.js, packages/fsweb/package.json, packages/fsweb/webpack.config.js, packages/pirateship/package.json, yarn.lock
This implements a few fixes to get PirateShip working on web again:
- Add babel.config to fsweb (current version of Babel doesn't appear to read from .babelrc anymore)
- Add uglify webpack plugin (was bundled with prior versions of Webepack)
- Add __DEFAULT_ENV__ to dev webpack config, defaults to production if not provided to keep behavior consistent with native
- Fix compile-web script in PirateShip to properly send platform argument to Flagship init
**Test:**
- `yarn ship:compile-web`
- Navigate to localhost:3000
- Switch the environment to Demandware, Shopify, or Mock to see data
=> feat(fsweb): get pirateship working again on web

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, yarn.lock
requires:
This updates the web MultiCarousel component to not render items if the item width is 0. This will prevent the items from displaying in a squashed state before the component has initialized and determined the proper item width.
=>  fix(fscomponents): hide web carousel if item width is 0

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
This adds the following for prev/next arrows on MultiCarousel:
- Added accessibility labels into FSI18N so they're not hardcoded strings
- Adds optional onblur property for use on web
=> feat(fscomponents): add onblur and translations to multi carousel arrows

.travis.yml
This removes the Xcode build phase of CI when code is pushed to master. This has been erroring due to issues with the PirateShip provisioning profile. After consideration, I decided that this was unnecessary as we already perform an iOS compile on pull requests so this shouldn't be needed as long as we follow proper protocol in requiring CI to pass before merging pull requests.
=> chore: remove xcode build from push ci step

packages/fsproductindex/src/components/ProductIndexProvider.tsx
Currently, the ProductIndexProvider component keeps a separate state variable for commerceData, which only gets updated if there are products to request reviews for. If there is an update where there were products before, but there no longer are, then the update does not make it through the provider.
=> fix(fsproductindex): Update commerce data even if no products

packages/fscomponents/src/components/Button.tsx
This reverts the SFC refactor from #415 as it introduced regressions such as not being to provide a palette as a prop to override the default styling. It does re-implement the accessibility update added in #587.
=> fix(fscomponents): revert buggy button refactor

packages/flagship/ios/FLAGSHIP/Info.plist
The changes put placeholders back for ios [script](https://github.com/brandingbrand/flagship/blob/master/packages/flagship/src/lib/ios.ts#L192) to add exception domains
=> fix(flagship): put placeholders back for using exception domains

packages/fsapp/package.json, packages/fsapp/src/components/Drawer.web.tsx
"isOpen" only tracks whether the drawer is open or closed, regardless of the animation transition. This adds a "drawerVisible" property for the wrapped component, which will allow the component to know whether it is displaying or not. This allows the component to, for example, hide itself when it isn't visible, to avoid being tabbed to.
=> feat(fsapp): Track whether the drawer is visible

packages/fsapp/package.json, packages/fsapp/src/components/Drawer.web.tsx
Reverts brandingbrand/flagship#658
@Cauldrath  - I'm not sure why I didn't catch this during testing but this is throwing errors for me consistently now when doing `yarn run ship:compile-web`:
```
index.ts:3 Uncaught TypeError: Cannot read property 'addEventListener' of null
at Drawer._this.animationRef (index.ts:3)
at HTMLUnknownElement.callCallback (index.ts:3)
at Object.invokeGuardedCallbackDev (index.ts:3)
at invokeGuardedCallback (index.ts:3)
at safelyDetachRef (index.ts:3)
at commitUnmount (index.ts:3)
at commitNestedUnmounts (index.ts:3)
at unmountHostComponents (index.ts:3)
at commitDeletion (index.ts:3)
at commitAllHostEffects (index.ts:3)
```
=> Revert "feat(fsapp): Track whether the drawer is visible"

packages/flagship/android/app/src/debug/AndroidManifest.xml, packages/flagship/android/build.gradle, packages/flagship/src/lib/modules/android/react-native-camera.ts, packages/flagship/src/lib/modules/android/react-native-firebase.ts
- Adds missing debug AndroidManifest file
- Changes playServicesVersion to 16.+
- Removes module scripts that change the gradle version
=> chore: react native 0.59 bug fixes

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx
The multi carousel is not showing when there's itemUpdated in the props
The initial opacity is set to 0 when there's itemUpdated in the props, but nothing triggers opacity change when first render
Trigger opacity change when first mounted if there's itemUpdated.
=> fix(fscomponents): ease in carousel when there is itemUpdated

packages/fsapp/src/types/index.ts
This PR adds the `initialTabIndex` property to `tabStyle`.
=> fix: add initialTabIndex prop to tabStyle

packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/inboxblocks/CTABlock.tsx, packages/fsengagement/src/inboxblocks/EventBlock.tsx, packages/fsengagement/src/inboxblocks/ImageBlock.tsx, packages/fsengagement/src/inboxblocks/ShareBlock.tsx, packages/fsengagement/src/inboxblocks/TextBlock.tsx, packages/fsengagement/src/types.ts
@deemaabdallah here is the fix for the flickering on the engagement list. There are two parts to the fix.
1.) Making some inbox block components PureComponents
I added shouldComponentUpdate functions to make sure extra re-renders don't occur. I had to use the function instead of PureComponent as each block gets all props so it would still re-render using PureComponent.
2.) adding key to flat list render item
As you scrolled since the keys didn't match it would re-create the element inside the flat list causing the flicker
=> fix: engagement flicker on scroll of items

packages/fsengage/package.json, packages/fslocator/package.json, yarn.lock
react-native-permissions released a breaking change with 1.2.0 (way to semver guys) that removes support for React Native's built in Async Storage in favor of having a peer dependency for the newly released react native community async storage. Because we do not currently have a dependency on the new async storage package this causes an error. (See: https://github.com/react-native-community/react-native-permissions/releases)
This PR pins react-native-permissions to the last good version until we have time to properly add support for the new async storage package.
=> chore: pin react-native-permissions version

packages/fsengagement/package.json
there are compile issues of 3.X react-native-video with Android when compiling with react-native 0.59. Version 4.x has better support with this react-native version for this library.
https://github.com/react-native-community/react-native-video#version-400-breaking-changes
=> fix(fsengagement): update react-native-video

packages/fsapp/src/fsapp/FSApp.tsx, packages/fsapp/src/fsapp/FSApp.web.tsx
When there is a collision between the path matching for other screens and the dev menu, this will make the dev menu take priority.
Cherry-pick of https://github.com/brandingbrand/flagship/pull/733
=> fix(fsapp): Put dev menu as first screen

packages/fsengagement/src/EngagementService.ts, packages/fsengagement/src/inboxblocks/VideoBlock.tsx
@bweissbart 
- by default save profileId in AsyncStorage (can for `getProfile` request by setting `forceProfileSync` to true)
- for Video component, handle optional props `fullscreen` and `muted`
=> feat(fsengagement): store engagement profileId

packages/fsweb/.babelrc, packages/fsweb/babel.config.js
Both metro-react-native-babel-preset and @babel/preset-env transpile "typeof", which causes it to include itself. This prevents the transpiling of typeof in @babel/preset-env. Also made the two babel configs work the same way
=> fix(fsweb): Prevent double transpiling of typeof

packages/fsapp/package.json, packages/fsapp/src/components/DevMenu.tsx, packages/fsapp/src/components/StorageManager.tsx, packages/fsapp/src/components/screenWrapper.tsx, packages/fscomponents/package.json, packages/fscomponents/src/components/SearchModal.tsx, packages/fscomponents/src/components/SearchScreen.tsx, packages/fsengagement/package.json, packages/fsengagement/src/EngagementService.ts, packages/pirateship/package.json, packages/pirateship/src/lib/persistReducer.ts, packages/pirateship/src/providers/recentlyViewedProvider.tsx, yarn.lock
AsyncStorage has been deprecated from React Native (https://facebook.github.io/react-native/docs/asyncstorage) so this adds dependencies to @react-native-community/async-storage and swaps out imports throughout Flagship. RN Link seems to be handling the native project changes properly so I haven't added any code to the iOS or Android templates.
Test by running ship:init and ship:run-ios or ship:run-android and then use the develop menu to check that data is being stored in AsyncStorage -- this is used in PirateShip for the product viewing history.
=> chore: swap out async storage dependencies

packages/fsnetwork/package.json, packages/fsshopify/package.json, yarn.lock
v0.19.0 of Axios [contains a regression](https://github.com/axios/axios/issues/2190) that prevents request-specific configuration from being applied. While this has been fixed by PR, a new release has not been made, so this pins Axios to the last good version 0.18.0.
=> feat: pin axios to 0.18.0

packages/fsengagement/src/inboxblocks/VideoBlock.tsx
@deemaabdallah  @bweissbart 
When `fullscreen` is passed as a prop, we trigger `presentFullscreenPlayer()` to launch the fullscreen player, then play it when the fullscreen callback fires.
=> feat(fsengagement): add fullscreen video option

packages/fsapp/src/components/screenWrapper.tsx
RNN v2 by default is passing static styling as a function so passProps info can be included. Updated to support the default behavior. This is not breaking the backward-compatible logic
=> fix(fsapp): RNN v2 allow passing static styling as a function

packages/flagship/src/lib/android.ts
android blocks http requests by default. the network security config was set up to work with
physical devices, but not emulators
=> fix: fix network security config for android emulators

packages/fsweb/dev-server/index.html
running default template wasn't loading css correctly unless you created index.html in your project
=> fix(fsweb): tag type of css bundle

packages/flagship/__tests__/mock_project/android/app/src/main/res/xml/network_security_config.xml, packages/flagship/src/lib/__tests__/android.test.ts
This test ensures that localhost, 10.0.2.2 (the Android emulator internal localhost IP), and any configured exception domains are added to the network security file in the Android project.
=> chore: add unit test for android exception domains

greenkeeper.json
This updates the Greenkeeper configuration to always ignore react-native updates, as we should never be merging in react-native updates without developer oversight. Syntax per the Greenkeeper docs: https://greenkeeper.io/docs.html#monorepo
=> chore: tell greenkeeper to ignore react-native updates

packages/fsnetwork/package.json, packages/fsshopify/package.json, yarn.lock
Axios 0.19 contains a bug in which custom request parameters are not actually applied to the request.
=> fix: pin axios to 0.18.x

packages/fsbazaarvoice/src/BazaarvoiceNormalizer.ts, packages/fscommerce/src/Review/types/Review.ts, packages/fscomponents/src/components/ReviewItem.tsx, packages/fscomponents/src/styles/ReviewItem.ts, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
Some reviews are syndicated by the manufacturer. When this is the case, if the client wants to display the indicator, another row will appear on the bottom of the review indicating that it is syndicated.
=> feat: update bv components w/ syndicated indicator

packages/fscomponents/src/components/CMSBanner.tsx
#244
https://github.com/brandingbrand/flagship/blob/master/packages/fscomponents/src/components/CMSBanner.tsx
Currently this component only defines a generic for props, meaning that components that extend CMSBanner cannot have their own state. We should update the type definition to add a state generic type.
Added type state for CMSBanner. Now we can use own state in component which are extends from CMSBanner.
=> chore: add state typing for component CMSBanner

packages/flagship/src/lib/__tests__/ios.test.ts, packages/flagship/src/lib/ios.ts
The init script was not updated to replace the new storyboard launch screen rather than the old xib.
The config option probably should also be updated to reflect the new storyboard expectation (ie.
rename `launchScreen.ios.xib` to something like `launchScreen.ios.storyboard`)
=> fix(flagship): Fix overwriting launch screen file

packages/fscomponents/src/components/ReviewItem.tsx
I needed to include the syndicationSource details in the renderSyndicatedIndicator prop
=> fix(fscomponents): add arg to bv syndication badge render prop

packages/pirateship/src/components/PSProductIndex.tsx
Description:
#143 
Happens when the product item heights differ (eg. product name wrapping, only some products having reviews, etc).
Changes:
Now gridlines are equals between products in Product Index
=> fix: Gridlines are misaligned between products in Product Index

packages/flagship/src/commands/init.ts, packages/fsweb/webpack.config.js
Resolve for issue #403
Now, the default env for webpack getting from generated config (config.web.json). Config generates by fsweb package and puts into web build directory. Then webpack get this generated config and set into web app.
=> fix: get default env from initial script

packages/fscommerce/src/Commerce/types/Cart.ts
#169 
It would be useful to have an itemCount that takes into account quantities of different items in count. could be implemented as a virtual using 'get' function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get
=> fix: Add itemCount to cart interface in fscommerce

packages/flagship/src/lib/modules/ios/react-native-leanplum.ts
There is a version mismatch between flagship and react-native-leanplum@4.0.0 here:
https://github.com/brandingbrand/flagship/blob/develop/packages/flagship/src/lib/modules/ios/react-native-leanplum.ts
https://github.com/brandingbrand/react-native-leanplum/blob/master/react-native-leanplum.podspec
Modify the podspec version to ve 2.6.2:
https://github.com/brandingbrand/flagship/blob/develop/packages/flagship/src/lib/modules/ios/react-native-leanplum.ts#L11
=> fix: Modify the podspec version to ve 2.6.2

packages/pirateship/env/common.js
The file had two different "name" members, so this removes the second one.
=> fix(pirateship): Remove duplicate "name" in config

greenkeeper.json
react, metro-react-babel-preset, and babel should only be updated as part of coordinated React Native upgrades.
=> chore: tell greenkeeper to ignore more dependencies

packages/flagship/src/commands/init.ts
The only file/directory with "flagship" in the name was the package directory, which is already being renamed when fixing the package directory structure.
Resolves https://github.com/brandingbrand/flagship/issues/895
=> fix(flagship): Fix renaming edge case for android

packages/pirateship/package.json, packages/pirateship/src/components/PSSignInForm.tsx, yarn.lock
#396 
The dependency react-native-touch-id was updated from 4.3.0 to 4.4.0
=> chore: Update react-native-touch-id dependency

packages/flagship/ios/fastlane/Fastfile
Added missing xcargs flags that tells xcode to make an unprovisioned build when "fastlane build" is executed.
=> fix(flagship): fix fastlane build lane

packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/pirateship/src/components/PSProductDetail.tsx
A reimplementation of the functionality that existed here
https://github.com/brandingbrand/flagship/commit/2391b829c6539080557f6c2631e33ae648754f4e
Allows us to pass in a custom content to be rendered upon zoom. This is necessary functionality to support client requirements.
Steps:
1. Run pirateship
2. set env to mock
3. navigate to ```/ProductDetail?productId=25752986``` (make sure productId is 25752989)
4. Click on the zoom button
Expected Result:
A simple Hello World, Close modal appears. Press Close to get rid of the modal. (to mock custom content that would be passed in)
Only productId 25752989 has a custom modal. Every other product uses the default ZoomCarousel content.
=> feat(fscomponents): Custom modal content in Zoom Carousel

greenkeeper.json
These types should be updated in sync with Flagship updates to the React and React Native libraries.
=> chore: tell greenkeeper to ignore react and react native types

packages/flagship/src/commands/init.ts, packages/flagship/src/lib/env.ts, yarn.lock
Usage: `yarn run init --env prod --onlyDefault`
Will only include the default env, which should reduce the size of production bundles by excluding the environments that aren't needed.
=> feat(flagship): Add option to only include the default env

packages/flagship/android/fastlane/Fastfile, packages/flagship/ios/fastlane/Fastfile, packages/flagship/src/lib/fastlane.ts, packages/flagship/src/types.ts
This deprecates the appcenter.apiConfig configuration option in favor of using the APPCENTER_API_TOKEN environment variable. This makes the key optional in the typedef and updates the Fastfiles for iOS and Android such that not including this option will not break the builds.
=> feat(flagship): deprecate appcenter.apiconfig configuration option

package.json, yarn.lock
This updates commitlint, jest, lerna, and typedoc to their latest versions. Because some of the concerns were not yet addressed by their parent packages, I also had to add custom resolutions for handlebars and https-proxy-agent.
=> chore: update dev dependencies to alleviate security issues

packages/fsbazaarvoice/src/BazaarvoiceNormalizer.ts
review.id is normalized from `ProductId` which is not unique, on the contrary, the values are usually the same because the reviews are usually from the same product. `Id` provides unique values so using this prop instead
=> fix(fsbazaarvoice): fix review id normalizer

.travis.yml, packages/flagship/__tests__/mock_project/ios/Podfile, packages/flagship/ios/Podfile
BREAKING CHANGE: This requires updating CocoaPods (including in CI) to v1.7.2+ in order for pod install to work with the CDN. This allows CocoaPods to pull from their own CDN which avoids rate limiting when pulling sources from GitHub instead.
=> feat: update podfile to use cocoapods cdn

packages/flagship/android/fastlane/Fastfile
the script is not smart enough to decide if a comma is required and causing build errors. For now, the easiest way to fix the errors is to rearrange these lines
=> fix: android fastline syntax error due to a trailing comma

packages/flagship/__tests__/mock_project/ios/Podfile, packages/flagship/ios/Podfile
BREAKING CHANGE: This requires updating CocoaPods (including in CI) to v1.7.2+ in order for pod install to work with the CDN. This allows CocoaPods to pull from their own CDN which avoids rate limiting when pulling sources from GitHub instead.
=> feat(flagship): update podfile to use cocoapods cdn

packages/fscomponents/src/components/SelectableRow.tsx
**Ticket:** https://jira.brandingbrand.com/browse/FLAGSHIP-63
Update SelectableRow to function component
- run fs test
=> refactor(fscomponents): FLAGSHIP-63 - Updating To Function Component

packages/fscomponents/src/components/Total.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-69
Total used to be a class-based component. This PR is to update it to a function component.
=> refactor(fscomponents): FLAGSHIP-69 Update to a function component

packages/fscomponents/src/components/TouchableDelay.tsx, packages/fscomponents/src/components/TouchableDelay.web.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-71
`TouchableDelay` should be an abstract class that are extended by `TouchableHighlightLink`, `TouchableOpacityLink` and `TouchableWithoutFeedback` in web applications.
=> refactor(fscomponents): FLAGSHIP-71 Change to abstract classes

packages/fscomponents/src/components/Selector/Selector.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-87
- add translations to Selector
- run fs tests
=> refactor(fscomponents): FLAGSHIP-87 update with translations

packages/pirateship/src/screens/Cart.tsx
The tabs got shifted over one when the "Home" tab was added, but the cart count was being applied to the same index. This makes the cart count show up on the cart icon.
=> fix(pirateship): Update tab index for cart count

packages/fslocator/src/components/LocatorContainer.tsx
This adds customized search function to fslocator and makes search endpoint optional. It allows users to use the component without query searching functionality.
=> feat(fslocator): add customized search functionality

packages/fscomponents/src/components/LoginForm.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-94
- add translations to loginform
- run fs tests
=> refactor(fscomponents): FLAGSHIP-94 Add Translations To Component

packages/fsbazaarvoice/package.json, packages/fsbazaarvoice/src/BazaarvoiceDataSource.ts, packages/fsbazaarvoice/src/BazaarvoiceReviewRequest.ts, packages/fscommerce/src/Review/types/ReviewQuery.ts
Added new optional params to the bazaarvoice review data source while leaving existing functionality in place.
Filter allows for multiple values following the "Filter=first&Filter=second&Filter=third" format.
Found no existing framework to create a test case in flagship. In the interest of time, I tested it directly within the CVS app.
=> feat(fsbazaarvoice): Expand review data source

packages/fsnetwork/src/__tests__/index.test.ts
Requesting the GitHub homepage with fsnetwork appears to consistently return a 406 error. This points the test at brandingbrand.com which resolves the error.
=> chore(fsnetwork): fix fsnetwork unit tests

packages/fsbazaarvoice/src/BazaarvoiceNormalizer.ts
ReviewStats had a defined property for recommendedRatio, but it was never actually populated.
Tested inside of the CVS app to make sure it works as expected.
=> feat(fsbazaarvoice): Add recommended ratio to normalized data

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts, packages/fscomponents/src/components/__stories__/ZoomCarousel.story.tsx
-Add prop to hide page indicators
-Fix issue where if fillContainer is set to true and showThumbnails is set to true, thumbnails won't show
-Add prop for custom styling for the fillContainer prop
-Add two stories to the storybook showing fillContainer prop for ZoomCarousel
=> feat(fscomponents): Add styling and prop options to ZoomCarousel

package.json, yarn.lock
typedoc 16 isn't compatible with the latest version of typedoc-plugin-monorepo (0.2.1 or 0.2.2), because it gets rid of OptionsReadMode. This change will allow build:docs to work again.
For reference, this is the line that blows up:
https://github.com/unstubbable/typedoc-plugin-monorepo/blob/7dc0fc86a8aae24b2c9e60a1a39a36c97de24083/external-module-map-plugin.ts#L68
=> fix(flagship): Downgrade typedoc to 15

packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts, packages/fscomponents/src/components/__stories__/ZoomCarousel.story.tsx
- Added a new option that can be rendered: image counter
--Absolutely placed component with custom rendering or custom styles as props
- Added new prop options for the carousel and image containers
- changed the default container styling to be flex friendly, fixing an issue where thumbnails would overflow beyond parent boundaries
Added some storybook options and also tested as a linked package inside of a test app.
=> feat(fscomponents): Add image counter, new style options to ZoomCarousel

packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/inboxblocks/CTABlock.tsx, packages/fsengagement/src/inboxblocks/FullScreenImageCard.tsx, packages/fsengagement/src/types.ts
- Adds the event emitter `swipeCard` when using a FullScreenImageCarousel card, emits an event when swiping to each new card.
- If available, send the position of the card with the events `viewLink` and `viewStory`
=> feat(fsengagement): add more event emitters and position data

packages/fscomponents/src/components/__stories__/ZoomCarousel.story.tsx
[ Story #1078](https://github.com/brandingbrand/flagship/issues/1078)
Added knobs to the zoom carousel story in storybook for the following props:
- images
- gapSize
- centerMode
- hideZoomButton
- fillContainer
- peekSize
- showArrow
- showThumbnails
**Testing**
- Pull down and run `yarn run dev:storybook`
- Open the Zoom Carousel story
- You can replace the current URLs with remote image URLs and interact with all of the props listed above
=> feat(fscomponents): Add knobs to zoom carousel story

packages/fscomponents/src/components/ShareButton/ShareButton.tsx, packages/fscomponents/src/components/ShareButton/ShareButton.web.tsx, packages/fscomponents/src/components/__stories__/ShareButton.story.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
react-native-web has support for the same Share api that react-native uses, but it isn't supported by all browsers (mostly just mobile ones):
https://caniuse.com/#feat=web-share
This will attempt to use that same api and, if it isn't available, attempt to copy the url to the clipboard.
=> feat(fscomponents): ShareButton web support

packages/fsengagement/src/EngagementComp.tsx
1. Use debounce to only allow a single click on EngagementComp
=> fix: add debounce to EngagementComp handleAction

packages/fscommerce/src/Commerce/CommerceProvider.tsx, packages/fscommerce/src/Commerce/types/Pageable.ts, packages/fsproductindex/src/components/ProductIndex.tsx, packages/fsproductindex/src/components/ProductIndexGrid.tsx
Currently you can load more, but if you start on a later page, you can not load previous pages. This adds that as an additional option and also adds a minPage value to Pageables, so that it can track the range of pages loaded with load more or load previous. Functionality should be unchanged for pages without load previous turned on or that don't look at the minPage value.
=> feat(fsproductindex): Add functionality for loading previous pages

packages/fscomponents/src/components/SearchBar.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
- add prop "initialValue" to allow the searchbar to be constructed with an initial value
- add a default ada label to the search button, with a prop to use a custom string
version 8 version of the PR
=> feat(fscomponents): add ada label and initial value prop to searh v8

packages/fscomponents/src/components/SearchBar.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
- add prop "initialValue" to allow the searchbar to be constructed with an initial value
- add a default ada label to the search button, with a prop to use a custom string
update needed for flagship v8.
=> feat(fscomponents): add ada label and initial value prop to searchbar

packages/fscomponents/src/components/Accordion.tsx, packages/fscomponents/src/components/__stories__/Accordion.story.tsx, packages/pirateship/src/components/PSAccordionGroup.tsx, packages/pirateship/src/screens/AccordionSample.tsx
There was an issue where the component would not update its size when the contents changed size. The most obvious case where this would fail is if you had two accordions nested with each other, opening/closing the inside one would not update the height of the outer one until you closed and opened it again. Also added the ability to put content inside of the accordion as a child instead of having to put it in the "content" prop and set title as a string instead of forcing a JSX.Element. This makes the component serializable as long as you avoid setting any styles. I also removed the titleHeight prop, because it didn't do anything, updated the comments to reflect the current state of the component, and updated the story and sample.
=> fix(fscomponents): Updated Accordion component

packages/fscomponents/src/components/PayPalCheckoutButton.tsx
Create serializable props interface for PayPalCheckoutButton component
=> feat: add serializable props to PayPalCheckoutButton component

packages/fsengagement/src/EngagementComp.tsx
The header is missing when deeplinking out of an engagement story
This happens because dismissAllModals is being called when changing tabs
Added a cleanup function componentWillUnmount to handle this interaction
=> fix(fsengagement): Header for discover start missing after deeplinking

packages/fsengagement/src/EngagementComp.tsx
The header is missing when deeplinking out of an engagement story
This happens because dismissAllModals is being called when changing tabs
Added a cleanup function componentWillUnmount to handle this interaction
This is adding functionality from #1322 to develop
=> fix(fsengagement): Header for discover missing after deeplinking

packages/fsapp/package.json, packages/fsapp/src/fsapp/FSApp.tsx, packages/pirateship/src/index.ts, packages/pirateship/src/lib/shortcuts.ts, yarn.lock
This PR includes a series of fixes that attempt to alleviate crashing when restarting the bundle on Android.
- Use BB fork of react-native-restart package which contains a fix to the Android code
- Wrap Navigation.setRoot() in fsapp inside runAfterInteractions which appears to help alleviate Navigation being clobbered on startup (inspired by https://github.com/wix/react-native-navigation/issues/3767#issuecomment-438029517)
- Refactor tab logic in fsapp so that tabs are generated before setting them in the Navigator
- Update tab schema to follow recommended format (https://github.com/wix/react-native-navigation/issues/5096#issuecomment-492032466)
- Removed non-printable character from PirateShip initialization config
- Removed setStackRoot() calls in PirateShip that were being used when …
=> fix: address android bundle restart crashes

packages/fsnetwork/package.json, yarn.lock
Version 0.19.x contains a regression in which Axios isn't properly retaining props to be passed to network requests.
=> feat: pin axios to 0.18.1

packages/flagship/src/lib/__tests__/ios.test.ts, packages/flagship/src/lib/ios.ts, packages/flagship/src/types.ts
Updated iOS config to support custom shortVersion build number
Added tests
This may require changes to iosExtension PR as well
This will allow builds for multi-tenant apps that are using different versions.
This is already possible with Android builds.
=> feat(flagship): Custom Short Version string for iOS

packages/fsapp/src/components/DevMenu.tsx
There is a bug in react-native-navigation where it can hang when it tries to close any open modals when restarting. (This line never calling the callback: https://github.com/wix/react-native-navigation/blob/a641b0976f18c54a0d649cf7905b6c83ab2ebf67/lib/ios/RNNModalManager.m#L70) This change closes the dev menu modal before trying to restart to avoid that issue. It could still occur if another modal is open, though, so this is an incomplete fix.
TEST
------------------
- run on iOS
- open the dev menu and either change the environment or click "Reload JS"
- should restart the application
=> fix(fsapp): Close dev menu before restart

packages/fscomponents/src/components/Carousel/Carousel.web.tsx, packages/fscomponents/src/components/__stories__/Carousel.story.tsx
If the carousel was empty, it would crash. This gives you a way to test it in the storybook and fixes the crash.
=> fix(fscomponents): Fix crash for empty carousel

packages/fscomponents/src/components/CartItem/CartItemDetails.tsx, packages/fscomponents/src/components/ProductItem/components/ProductItemPrice.tsx, packages/fscomponents/src/components/ProductMetadata.tsx, packages/fscomponents/src/components/Total.tsx
If your currency code was invalid, it would crash the app when it tried to render. This wraps those conversions in a try/catch, so it will put the error in the console and display as if the currency value was undefined instead of crashing.
=> fix(fscomponents): Fix crashes with bad currency codes

packages/flagship/src/commands/init.ts, packages/flagship/src/lib/ios.ts
This adds a script to iOS init that patches RCTUIImageViewAnimated.m to display images in iOS 14.
See issue here: https://github.com/facebook/react-native/issues/29268
1. Download Xcode 12 Beta
2. Select the Xcode 12 build environment (`sudo xcode-select -s /Applications/Xcode12-Beta.app/Contents/Developer/`)
3. `yarn && yarn ship:init`
4. Open PirateShip in Xcode 12 Beta
5. Select an iOS 14 simulator
6. Run the app in Xcode (you may have to run the packager from the command line manually first)
7. Verify that images appear as expected in the app
=> fix(flagship): add init script to patch rn images for ios 14

packages/fscomponents/src/components/Accordion.tsx
`JSX.Element` is not a serializable property
=> fix(fscomponents): fix serializable accordion props

packages/flagship/android/build.gradle, packages/pirateship/package.json
This adds a block to build.gradle to set the Android build tools version for subprojects (from external dependencies). This addresses a build error in release mode in which libraries are attempting to reference Material UI. This appears to be the community-supported resolution to this problem: https://stackoverflow.com/a/53371395
This also runs Jetify whenever init runs because this is a required step for builds to work.
=> fix: resolve android build tools in subprojects

packages/flagship/android/fastlane/Fastfile
This removes the destination_type line from the Android fastfile which prevents distribution to groups which is our most common use case. This will default to "group" but can be customized with the APPCENTER_DISTRIBUTE_DESTINATION_TYPE environment variable.
=> fix: appcenter upload groups for android

packages/fscomponents/src/components/SearchModal.tsx, packages/fscomponents/src/components/SearchScreen.tsx, packages/pirateship/src/screens/Search.tsx
Almost all the code in SearchModal is identical to the code in SearchScreen, just with the Modal wrapper added and a few less options. This makes the SearchModal wrap a SearchScreen in a Modal, which allows those same options to work with SearchModal and removes repeated code. The result should be no changes to how the SearchModal works, except for the addition of some options in SearchScreen that weren't there before.
Also fixed some typing in SearchScreen and PirateShip's Search screen. brandPartSuggestions was referring to some old code that isn't part of fscommerce anymore, so that was removed as it is no longer part of the applicible types.
=> fix(fscomponents): Remove redundant code in SearchModal

package.json, packages/fsapp/package.json, packages/fsapp/src/components/screenWrapper.web.tsx, packages/fscommerce/src/index.ts, packages/fscomponents/src/components/PayPalCheckoutButton.tsx, yarn.lock
BREAKING CHANGE: This upgrades Typescript from 3.x to 4.x which includes changes that are for edge cases but still breaking nonetheless. The full changelog can be found here: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#breaking-changes
Fixed a couple instances where TypeScript recognized that we were always overriding variables by using the spread operator. Also addressed a couple places where we were importing `default` even though no such export existed.
=> feat: FS-1314 - upgrade typescript to 4.0.2

.dependabot/config.yml
These versions are dependent on the current version of React Native and therefore shouldn't be upgraded automatically.
=> chore: tell dependabot to ignore react-native-cli

package.json, packages/flagship/android/app/src/main/AndroidManifest.xml, packages/flagship/src/lib/ios.ts, packages/flagship/src/lib/modules/android/react-native-permissions.ts, packages/flagship/src/lib/modules/ios/react-native-permissions.ts, packages/flagship/src/lib/usage-descriptions.ts, packages/flagship/src/types.ts, packages/fsengage/package.json, packages/fsengage/src/modules/cms/requesters/contentManagementSystemLocatorPermission.ts, packages/fslocator/package.json, packages/fslocator/src/lib/getLocationPermission.ts, packages/pirateship/env/common.js, packages/pirateship/package.json, yarn.lock
BREAKING CHANGE: This upgrades react-native-permissions from v1 to v2 and adds config support for adding the appropriate pods and permissions to the ios and android projects. Permissions v2 has a new API that will require changes for existing implementations.
Usage of the library is described in their repo: https://github.com/react-native-community/react-native-permissions#methods
In v1 of permissions, support for every permission is included out of the box. In v2, you opt into individual permissions as needed. This PR adds a new key to the config, `permissions`, which allows you to specify what to support. Here's an example:
```
permissions: {
ios: {
LOCATION_WHEN_IN_USE: 'Test Description'
}
android: [
'ACCESS_FINE_LOCATION'
]
}
````
For iOS, you provide an object keyed by the …
=> feat: implement react-native-permissions v2 support

.travis.yml
This moves commitlint to the end of the commands run to validate PRs. This way we can see if the "real" tests pass first even if commitlint fails.
=> chore: reorder ci test commands

packages/fscheckout/src/components/StepTracker.tsx, packages/fscomponents/src/components/Accordion.tsx, packages/fscomponents/src/components/ModalHalfScreen.tsx, packages/fscomponents/src/components/SearchBar.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarouselItem.tsx, packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/EngagementProductModal.tsx, packages/fsengagement/src/inboxblocks/FullScreenImageCard.tsx, packages/fsengagement/src/inboxblocks/InboxWrapper.tsx, packages/fsengagement/src/inboxblocks/RoundedImageCard.tsx, packages/fslocator/src/components/LocatorMapSlideList.tsx
Per the React Native docs, using the native driver for animations will only work for non-layout transforms like opacity and rotation. RN appears to have silently ignored invalid transforms in the past, but in RN 63 it displays a promiment warning. This updates all invalid transforms using native drivers to set useNativeDriver to false.
Reference which is from 2017 but still appears to be valid per my research: https://reactnative.dev/blog/2017/02/14/using-native-driver-for-animated.html#caveats
=> fix: audit usenativedriver settings for animations

packages/fsengage/package.json, packages/fsengage/src/modules/cms/requesters/contentManagementSystemLocatorPermission.ts, packages/pirateship/env/common.js, packages/pirateship/package.json
fsengage is a dependency on a number of fs packages, and fsengage had a hard dependency on react native permissions due to its geolocation handler for the core cms provider. react-native-permissions requires native setup and exposes itself to end users, which is not ideal given that most projects that use fsengage don't need geolocation functionality. This PR makes permissions a peer dependency and updates the geolocation handler to return false if react native permissions isn't available in the project.
=> feat: make permissions a soft dependency in fsengage

packages/fsengagement/src/EngagementComp.tsx
This addresses a warning regarding updating state on an unmounted component in EngagementComp. It adds a simple boolean keeping track of whether the component is currently mounted so that async operations can check before running.
=> fix(fsengagement): address cannot set state on unmounted component error

.storybook/webpack.config.js, package.json, packages/fsapp/package.json, packages/fscomponents/package.json, packages/fsengagement/package.json, packages/fstestproject/package.json, packages/fsweb/webpack.config.js, packages/pirateship/package.json, yarn.lock
Web support was added in 1.9.0. This is updating to 1.12.0 in the yarn.lock, though.
=> fix(fsweb): Update to newer version of async-storage

.storybook/webpack.config.js, packages/fscomponents/package.json, packages/fscomponents/src/components/AddressForm.tsx, packages/fscomponents/src/components/CMSFeedback.tsx, packages/fscomponents/src/components/ChangePasswordComponent.tsx, packages/fscomponents/src/components/CreditCardForm.tsx, packages/fscomponents/src/components/EmailForm.tsx, packages/fscomponents/src/components/Form/Form.tsx, packages/fscomponents/src/components/LoginForm.tsx, packages/fscomponents/src/components/PromoForm.tsx, packages/fscomponents/src/components/RegistrationForm.tsx, packages/fscomponents/src/components/UpdateNameOrEmail.tsx, packages/fscomponents/src/components/__stories__/Form.story.tsx, packages/fsweb/webpack.config.js, packages/pirateship/package.json, packages/pirateship/src/components/ContactInfoForm.tsx, packages/pirateship/src/components/PSAddressForm.tsx, packages/pirateship/src/components/PSCreditCardForm.tsx, packages/pirateship/src/components/PSSignInForm.tsx, packages/pirateship/src/screens/EmailSignUp.tsx, packages/pirateship/src/screens/ForgotPassword.tsx, packages/pirateship/src/screens/TrackOrderLanding.tsx, yarn.lock
tcomb-form-native hasn't been updated in several years and therefore still had dependencies on React Native that had been moved to separate packages as part of the RN lean core project.
We created a Branding Brand fork, @brandingbrand/tcomb-form-native, that addresses these issues. This updates Flagship to use the forked version.
=> feat: replaced tcomb-form-native with bb fork

packages/fsweb/polyfills/navigator.js, packages/pirateship/src/index.web.ts
Needed for react-native-localize to run server-side. Also removed a console.log
=> fix(fsweb): Add languages to navigator

packages/fsweb/package.json, yarn.lock
This updates the version number for @react-native-community/datetimepicker to 3.0.2 to bring it in sync with the version required by @brandingbrand/tcomb-form-native.
=> fix(fsweb): bump datetimepicker version

packages/fsapp/src/lib/ssr.ts, packages/fsapp/src/types/index.ts, packages/pirateship/src/ssr.ts
Can now set options to call next() on certain screens, so middleware after the SSR can run. Also allows turning off rendering the app for the root path and overriding the html that is used as the base, in case the file is in a different location or you want to pass in some other string.
=> feat(fsapp): Add additional options to SSR

packages/fscomponents/src/components/NestingButtons.tsx, packages/fscomponents/src/components/__stories__/NestingButtons.story.tsx
Accepts an array of button props and generates buttons based on those. If the number of buttons
exceeds a configurable threshold, the buttons will be hidden behind a modal.
=> feat(fscomponents): add NestingButtons component

packages/flagship/src/lib/modules/ios/react-native-firebase.ts
- the `react-native-firebase` module was adding `Firebase/Core 5.1.2` to the Podfile
- this was causing a build error because the react-native 60+ is dependent on iOS SDK 6.13+ 
- updating to add 6.13 to the Podfile and its dependency `pod 'GoogleAppMeasurement', '6.1.6'`
from https://www.npmjs.com/package/react-native-firebase
=> fix(flagship): update RNFirebase pod

packages/flagship/android/app/src/debug/java/com/brandingbrand/reactnative/and/flagship/ReactNativeFlipper.java, packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/MainApplication.java, packages/flagship/src/commands/init.ts, packages/flagship/src/lib/path.ts
- adds path function to get debug android src folder
- adds init step to rename debug src folder structure to match package
- fixes flipper package name
- moves flipper to only be included in debug
=> fix: fix android release variant compilation

packages/fsnetwork/package.json
Axios v0.20.0 introduces some bugs which fails several actions. They are resolved in v0.21.0.
**Note:** This version doesn't include any new features or breaking changes.
**Release change logs:** https://github.com/axios/axios/releases/tag/v0.21.0
=> chore(fsnetwork): upgrade axios to 0.21.0

packages/flagship/src/lib/modules/android/react-native-camera.ts
react-native-camera needs a missingDimensionStrategy line added to build.gradle to build properly. Our script to patch this was looking to do a string replace on a value that no longer exists in the file.
=> fix(flagship): made rn camera patch script work again

.storybook/webpack.config.js, package.json, packages/fsweb/package.json, packages/fsweb/webpack.config.js, yarn.lock
react-native-svg has web support now, so a separate module isn't needed.
=> fix(fsweb): Remove svgs module

packages/fscomponents/src/lib/__tests__/helpers.test.ts
Currently it is not possible to complete testing in the MST Timezone due to the way that Date uses the system's TZ. This removes the absolute time zones as well as fixes a few typos to get the test to pass as expected.
=> Format Hours Test Fixes

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx
The onTouch and onMouse events, as well as className, are no longer supported by react-native-web. This changes that element to be a React div, which will support them.
=> fix(fscomponents): Use div for web multicarousel

packages/fsapp/src/components/DrawerRouter.web.tsx, packages/fsapp/src/components/NotFound.tsx, packages/fsapp/src/fsapp/FSApp.tsx, packages/fsapp/src/types/index.ts, packages/pirateship/src/appConfig.ts
When failing to find a matching path, this adds a fallback catchall route that will either redirect to a given screen with setStackRoot or call popToRoot. Generally you will only use setStackRoot with single screen apps, because it will make any tabs redirect to that same screen, while popToRoot will go to the initial screen for a given tab.
=> feat(fsapp): notFoundRedirect

packages/fsapp/src/components/DrawerRouter.web.tsx, packages/fsapp/src/fsapp/FSApp.tsx, packages/fsapp/src/types/index.ts
Allows passing a screen to notFoundRedirect config. Effectively works as a 404 page.
=> feat(fsapp): Screen option for notFoundRedirect

packages/flagship/src/lib/android.ts, packages/flagship/src/types.ts
Uses code from:
https://reactnative.dev/docs/0.62/image#gif-and-webp-support-on-android
By default, apps will now include support for both formats. Add build.gifSupport=false to turn off gif support and/or build.webPSupport=false to turn off WebP support.
=> feat(flagship): Support for gifs and WebP in Android

packages/fscomponents/src/components/Carousel/Carousel.web.tsx
This fixes an odd regression in which the Carousel component for web is only displaying one image. The cause seems to be that using <View> causes react-native-web to create a <div> with a class attached; this class seems to prevent the react-id-swiper library from binding to the slide. This replaces the <View> with <div> which seems to resolve the problem.
Test:
1. Run `yarn dev:storybook`
2. Navigate to the Carousel story
3. Verify that the Carousel story displays multiple slides
=> fix(fscomponents): fix web carousel only showing one image

packages/fsapp/src/lib/ssr.ts
BREAKING CHANGE:
Fix the rendering on the server side when the body or variables contain $1 instances.
- set any variable in the initial data function that contain a string with `$1`, e.g. `test = 'the price is $100 - $125'`
- render some text element that contain a string `$1`, e.g. `<Text>the price is $100 - $125</Text>
- load the page and view source.
ER: the variables are rendered as JSON correctly, the page body is rendered correctly.
=> fix(ssr): fix server side rendering of the $1 instances

packages/fsapp/src/components/DrawerRouter.web.tsx
Allows for a screen to have multiple routes for web.  This won't adversely affect screens with a single route.  Allows for something like:
```
'/pindex/:categoryId': {
screen: 'ProductIndex',
passProps: {
query: {
categoryId: 'categoryId'
}
}
},
'/men': {
screen: 'ProductIndex',
passProps: {
query: {
categoryId: 'fdefc46a-0a0b-499f-a8fd-e9a24179048a'
}
}
},
'/women': {
screen: 'ProductIndex',
passProps: {
query: {
categoryId: '7524c674-8635-47d9-a844-4fc2fe3c575e'
}
}
}
```
=> feat: allow screens to have multiple routes

packages/fscommerce/src/Commerce/types/CategoryQuery.ts
RELATED PR:
https://github.com/brandingbrand/submarine/pull/257
The query for fetchCategory function can specify 'levels' parameter to get more levels of categories.
This allows to avoid additional requests in some cases when we need to get more than 2 levels of categories,
that are provided by default.
=> feat(category): allow fetchCategory query to have levels parameter

packages/fscommerce/src/Commerce/types/ProductQuery.ts, packages/fscomponents/src/components/FilterList/FilterListDrilldown.tsx, packages/fsmockdatasources/src/commerce/mixins/ProductCatalog.ts, packages/fsproductindex/src/components/ProductIndexGrid.tsx, packages/fstestproject/src/screens/fscommerce/MockCommerceDataSource.tsx
When sorting, if no refinements were applied, it would check the keys of the undefined refinements and crash. This adds proper typing to the sort handling and the appropriate check.
=> fix(fsproductindex): Fix typing and add check

packages/flagship/ios/FLAGSHIP.xcodeproj/project.pbxproj, packages/flagship/src/lib/__tests__/ios.test.ts
Flagship only supports iOS on the Apple side, so we should only be targeting TARGETED_DEVICE_FAMILY="1" in the pbxproj file. We were incorrectly targeting 1,2 which corresponds to a universal app.
I also added a unit test to try to avoid any regressions in the future.
=> fix(flagship): set proper device targets in ios template

packages/flagship/src/lib/ios.ts
Ticket: https://brandingbrand.atlassian.net/browse/FS-1893
1. Update global regex to look for `TARGETED_DEVICE_FAMILY = "1,2"`
=> [FS-1893] Update Targeted Devices Wrong Regex

packages/flagship/src/commands/init.ts, packages/flagship/src/lib/ios.ts
cherry-pick first commit from this PR: https://github.com/brandingbrand/flagship/pull/1865
React-native has been updated with its own fix for this issue, with a slight difference:
```
if (_currentFrame) {
layer.contentsScale = self.animatedImageScale;
layer.contents = (__bridge id)_currentFrame.CGImage;
} else {
[super displayLayer:layer];
}
```
vs
```
if (_currentFrame) {
layer.contentsScale = self.animatedImageScale;
layer.contents = (__bridge id)_currentFrame.CGImage;
}
[super displayLayer:layer];
```
The version without the else was breaking gifs on iOS 12, so this removes the patch.
=> fix(flagship): Remove animated image patch

package.json, yarn.lock
This upgrades Immer to resolve a security alert. Immer is a dependency that's required for React Storybook through a couple different channels. This PR upgrades @storybook/react to the latest version (not a breaking change) which removes the direct dependency to Immer. It also manually resolves Immer to the latest patched version, because react-dev-utils (another dependency of Storybook) has not updated their Immer dependency yet.
=> chore: upgrade immer dependency for security

packages/fsweb/src/lib/proxy.ts
For cases where there are endpoints on multiple paths, this allows you to specify multiple ones. Complex paths aren't really supported because they need to fit both path-to-regexp and http-proxy's target, which uses the url module. This also allows you to specify endpoints on different domains, if they have different paths.
=> feat(fsweb): Add support for an array of endpoints

packages/fscomponents/src/components/serializable/SerializableImage.tsx
This fixes a bug with SerializableImage where when a given hight is specified it would ignore it unless `onPress` was also provided.
=> fix(fscomponents): serializable image styling

packages/fscommerce/src/Commerce/types/Cart.ts
Salesforce API provides information about bonus discount line items in the data for the cart.
We update the types for the Cart and CartItem for that data.
=> feat(fscommerce): types for salesforce bonus discount line items

packages/fscomponents/src/lib/style.ts
This fixes the style extractors so they work with React Native Web `number` based style props.
=> fix(fscomponents): style extracter

packages/fsengagement/src/inboxblocks/CustomCarouselBlock.tsx, packages/fsengagement/src/inboxblocks/ImageCarouselBlock.tsx
Found a bug where if there is an image of a certain height above a carousel it causes the carousel to try to continuously change its height by a tiny amount, causing it to become unusable.
=> fix(fsengagement): fix twitching on carousels

packages/fsapp/src/beta-app/app/app.ts, packages/fsapp/src/beta-app/development/dev-menu.component.web.tsx, packages/fsapp/src/beta-app/router/context/activated-route.context.tsx, packages/fsapp/src/beta-app/router/history/history.ts, packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/history/utils.native.tsx, packages/fsapp/src/beta-app/router/router.tsx, packages/fsapp/src/beta-app/router/router.web.tsx, packages/fsapp/src/beta-app/router/types.ts, packages/fsapp/src/beta-app/router/utils.ts, packages/fsapp/src/beta-app/utils.base.tsx
This includes several native fixes for deep linking
This renames `lazyComponent` to `loadComponent` and passes the activated route as a parameter for advanced dynamic components
=> feat(fsapp): native deep linking fixes 

packages/fscommerce/src/Commerce/interfaces/CartDataSource.ts, packages/fscommerce/src/Commerce/sessions/CommerceCookieSessionManager.web.ts, packages/fscommerce/src/Commerce/sessions/CommerceSessionManager.ts, packages/fscommerce/src/Commerce/types/Cart.ts, packages/fscommerce/src/Commerce/types/CartQuery.ts, packages/fscommerce/src/Commerce/types/Product.ts
BREAKING CHANGE:
- allow only one invocation of the session manager `get` method at a time.
- provide types for the `fetchCart` method to allow only one invocation of the method at a time.
Test together with the related PR.
https://github.com/brandingbrand/submarine/pull/365
=> fix(fscommerce): session manager

packages/fscomponents/src/lib/style.ts
This fixes the false positives that `borderWidth` was getting via `/width/i` which was separating it form the `borderColor` and other border props.
=> fix: host border props

packages/fsapp/src/beta-app/router/history/utils.native.tsx, packages/fsapp/src/beta-app/router/router.tsx, packages/fsapp/src/beta-app/router/router.web.tsx, packages/fsapp/src/beta-app/router/types.ts
@bweissbart debugging session with @wSedlacek led to the need to include the root stack id to enable switching tabs via `navigator.open` on native
=> fix: add stack id to enable tab switching on native

packages/fscomponents/src/components/serializable/SerializableButton.tsx
This fixes button linking not triggering due to `onPress` always being defined.
=> fix(fscomponents): button linking

packages/flagship/src/lib/modules/ios/react-native-permissions.ts
Ticket: https://brandingbrand.atlassian.net/browse/FS-2158
1. The current `usageDescriptionKey` for App Tracking Transparency is `NSAppleMusicUsageDescription` which is incorrect and will render an error message if you attempt to request the ATT permission.
2. Replace `NSAppleMusicUsageDescription` with `NSUserTrackingUsageDescription` per https://developer.apple.com/documentation/bundleresources/information_property_list/nsusertrackingusagedescription and https://github.com/zoontek/react-native-permissions#ios
=> [FS-2158] Incorrect usageDescriptionKey for App Tracking Transparency Permission

packages/flagship/src/lib/ios.ts
Ticket: https://brandingbrand.atlassian.net/browse/FS-2160
1. Update extension `Info.plist` `CFBundleShortVersionString` to be `shortVersion` to be consistent with iOS app `Info.plist`
2. For apps that do not use `package.json` `version` as the actual version in the app will run into the following error:
```
WARNING ITMS-90473: "CFBundleShortVersionString Mismatch. The CFBundleShortVersionString value '1.0.0' of extension 'LeviStraussAmericasApp.app/PlugIns/Notifications.appex' does not match the CFBundleShortVersionString value '##.##.##' of its containing iOS application '<app_name>.app'
```
=> [FS-2160] Update All CFBundleShortVersionString To Be shortVersion

packages/fscomponents/src/lib/style.ts
Ticket: https://brandingbrand.atlassian.net/browse/FS-2071
This fixes the padding behavior so that it is on the inside of the host.
=> fix: FS-2071 - remove padding from host style

packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/types.ts, packages/fsapp/src/beta-app/router/utils.ts
@bweissbart @wSedlacek 
- change type `Tab` to be a tab object only (not a string)
- set tabAffinity to be the id of the tab instead of the title
=> fix: use tab id instead of title for tabAffinity

packages/fsapp/src/beta-app/development/dev-menu.component.web.tsx, packages/fsapp/src/beta-app/router/history/history.ts, packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/history/utils.native.tsx, packages/fsapp/src/beta-app/router/index.ts, packages/fsapp/src/beta-app/router/router.tsx, packages/fsapp/src/beta-app/router/router.web.tsx, packages/fsapp/src/beta-app/router/types.ts, packages/fsapp/src/beta-app/router/utils.ts, packages/fsapp/src/beta-app/utils.base.tsx
@bweissbart @wSedlacek  This should eliminate the need for having the tab path prefixed to the child routes, while maintaining the proper tabAffinity.
A tabbed route (RouteCollection type) would not have a `path` but instead would have an `initialPath` that must match one of its children.
If we wanted a set of routes such as
`/shop`
`/c/:categoryId`
`/p/:productId`
to be in the Shop tab we would write the routes file like:
```
{
initialPath: 'shop',
tab: Shop,
children: [
{
path: 'shop',
title: TITLE,
loadComponent: () => import('./screens/Shop').then(({ Shop }) => Shop),
topBarStyle: { ...defaultTopBar, ...headerNoDivider }
},
{
path: 'c/:categoryId',
title: ({ data }) => (typeof data.title === 'string' ? data.title : TITLE),
loadComponent: () => import('./screens/Category').then(({ …
```
=> feat: allow beta router to handle univeral links with need for prefix

packages/fsengage/package.json, packages/fsengage/src/modules/analytics/Analytics.ts, packages/fsengage/src/modules/analytics/providers/AnalyticsProvider.ts, packages/fsengage/src/modules/analytics/providers/google/GoogleAnalyticsProvider.ts, yarn.lock
Depends on: https://github.com/brandingbrand/react-native-google-analytics/pull/15
example:
```js
// params to be parsed from url
Analytics.setTrafficSource({
id: params.utm_id,
source: params.utm_source,
medium: params.utm_medium,
campaign: params.utm_campaign,
term: params.utm_term,
content: params.utm_content
});
```
=> feat(fsengage): FS-2222 add ability to set traffic attribution data

packages/fsweb/src/server.prod.ts
if a route isn't handled by one of the middlewares (eg. static files, proxy), deliver the react
bundle. the application router will handle rendering the proper content.
=> fix(fsweb): deliver react bundle on all fall-through requests

packages/fscomponents/src/styles/index.ts
`./variables` already exports `weights` and metro throws the following error with this conflict in some circumstances.
```
TypeError: Attempting to change the getter of an unconfigurable property
```
This fixes that.
=> refactor(fscomponents): remove duplicate export

tsconfig/tsconfig.base.json
This makes the comments public so that JS Doc comments are not removed from bundles.
This means that hover over docs in VS Code will work.
This means that Serializable Components will not have their `TJS-Ignore` comments removed﻿
=> feat: public js docs

packages/fscomponents/src/components/serializable/vNext/SerializableImage.tsx
This replaces the plain SerializableImage component to one that accept children and can act as an overlay.  If you haven't used the `ImageBackground` component much before the code for it is here: https://github.com/facebook/react-native/blob/master/Libraries/Image/ImageBackground.js
It's basically a wrapped/styled Image component and it does have web support.
- remove height/width from the image `source`.  We really should never have been passing it in with the source object, it's why we need the ImagePropsTransformer in the app to undo this.  Instead it should only be in the style object
- I wrapped `ImageBackground` in another view because it allows padding (and possibly a background color) for the image, which is I believe what a user would expect when adding padding (see picture). …
=> feat(fscomponents): FS-2308 - allow serializableImage to have children

packages/fsapp/src/beta-app/utils.base.tsx
The following route was being registered as `shop/shop/category/:categoryId`.
```ts
{
initialPath: 'shop',
tab: Shop,
children: [
{
path: 'shop/category/:categoryId',
loadComponent: () => import('./screens/Category').then(({ Category }) => Category)
},
]
}
```
With the `initialPath` prepended when it shouldn't have been.
This fixes that.
=> fix(fsapp): broken links

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts, packages/fscomponents/src/components/__stories__/ZoomCarousel.story.tsx
- added new prop to hide horizontal overflow in the carousel
- added storybook example
Accidentally pushed this up to the repo, please delete during merge.
This is specifically for flagship 10. I will make a PR for flagship 11.
=> feat(fscomponents): add ability to hide overflow in multi carousel

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts, packages/fscomponents/src/components/__stories__/ZoomCarousel.story.tsx
- optional prop for horizontal scroll, allows for movement exclusively by left right swipes
This is the same as https://github.com/brandingbrand/flagship/pull/2104, but for v11
=> feat(fscomponents): add ability to hide oveflow on carousel

packages/fsapp/src/beta-app/router/history/history.ts, packages/fsapp/src/beta-app/router/history/types.ts
This fixes the native .updateTitle() function to properly affect the current location rather than the component registration for the current path.
This adds a new parameter to specify which componentId to affect.﻿
=> fix(fsapp): updating title

.travis.yml
The build storybook step of CI was failing because fscomponents had a dependency on fsapp, and fsapp has a dependency on project_env_index.js being set. project_env_index.js is created as part of the init process. This adds init to the test stage to address the error.
=> chore: fix travis builds

packages/flagship/__tests__/mock_project/android/fastlane/Fastfile, packages/flagship/android/fastlane/Fastfile
This lane made a couple incorrect assumptions about making android app bundles.
1. It called the gradle task assembleBundle which isn't a real task -- the task name is bundleRelease
2. It tried to perform an Appcenter Upload, but Appcenter can only handle APKs not AABs
At this time our existing Fastlane processes will continue to work to upload APKs to Appcenter.
=> chore: remove appcenter_app_bundle lane from android template

packages/create-fs-app/package.json, yarn.lock
This updates tar 4.4.x and tar 5.0.x to their latest versions to fix a security issue.
=> chore: security fixes for tar

packages/fsapp/src/beta-app/router/utils.ts
This catches (and warns) when externalRoutes throws.
This assures that errors like the API being unreachable do not cause applications to fall over.﻿
=> fix(fsapp): catch external route promises

packages/flagship/android/app/src/main/AndroidManifest.xml, packages/flagship/src/lib/android.ts, packages/flagship/src/lib/deeplinking.ts
This fixes the intent filters for deep linking on android.
This allows for linking like
```
app://some/path
```
and
```
https://somewebsite.com/some/path
```
within the same app.
=> fix(flagship): deep linking on android

packages/fsapp/src/beta-app/router/history/history.ts
- On Android, we had an order of operations issue where promises would resolve before they were being listened for.
- This fixes Android routing
- ⚠️ Without this fix, Android routing will be totally broken
=> fix: issue with promises resolving before heard

scripts/getNextAlphaVersion.js, scripts/publishAlpha.sh
This adds a bash script to aide in publishing alpha versions. If no version is specified, it will parse the lerna.json file to determine the next alpha version. If a version is specified, it will use said version. In either case it will invoke Lerna with the default flags we want for publishing alpha versions (dist-tag, allow-branch, and exact).
=> chore: add convenience scripts for publishing alpha versions

packages/fsengagement/src/carousel/RenderImageTextItem.tsx, packages/fsengagement/src/inboxblocks/IconTextBlock.tsx, packages/fsengagement/src/inboxblocks/ImageWithOverlay.tsx
In a previous PR we began passing context into class components as a prop but I forgot to change the usage to pull from props instead of the old context.
=> fix: context fix for engagement components

packages/flagship/android/build.gradle, packages/flagship/android/fastlane/Fastfile, packages/flagship/src/lib/fastlane.ts, packages/pirateship/env/common.js
BREAKING CHANGE: This updates the Android base project to target API level 30. Per Google's documentation, app updates will no longer be accepted unless they target level 30 as of November 2021. As such, this is being included as a feature release instead of a new breaking version.
This PR also introduces a new Fastlane lane to build Android App Bundles (AABs) called appcenter_bundle.
=> feat: target android api 30 and add aab support

packages/flagship/android/build.gradle, packages/flagship/android/fastlane/Fastfile, packages/flagship/src/lib/fastlane.ts, packages/pirateship/env/common.js
BREAKING CHANGE: This updates the Android base project to target API level 30. Per Google's documentation, app updates will no longer be accepted unless they target level 30 as of November 2021. As such, this is being included as a feature release instead of a new breaking version.
This PR also introduces a new Fastlane lane to build Android App Bundles (AABs) called appcenter_bundle.
=> feat: target android api 30 and add aab support [v10.x]

packages/flagship/src/lib/modules/ios/react-native-navigation.ts
iOS15 introduced a new appearance setting, scrollEdgeAppearance, that dictates the style of the tab bar when scroll content is aligned with the tab bar. React Native Navigation v6 does not handle this property, so the tab bar gets a black background when the user scrolls to the bottom of the screen.
This PR adds a patch script that patches react-native-navigation to apply the same tab bar styling to the scrollEdgeAppearance settings as well to allow for a consistent tab bar style regardless of scroll state.
This problem was fixed in react-native-navigation v7 but this allows us to continue supporting Flagship 10 and 11 which depend on v6.
=> feat(flagship): add navigation patch to support ios 15

package.json, packages/fscomponents/package.json, packages/fscomponents/src/components/Carousel/Carousel.web.tsx, packages/fscomponents/src/components/__stories__/Carousel.story.tsx, packages/fscomponents/src/components/typings.d.ts, packages/fsweb/package.json, packages/pirateship/src/screens.tsx, packages/pirateship/src/screens/CarouselSample.tsx, packages/pirateship/src/screens/Development.tsx, yarn.lock
This updates the Swiper dependency to fix a security issue. The fixed version is a breaking change from the previous (v5 to v6) which in turn broke our custom implementation which uses react-id-swiper in conjunction with Swiper. (The pagination buttons were no longer displaying.)
I refactored the web carousel code to use the "custom build" solution described in the react-id-swiper readme and it solved the problem: https://www.npmjs.com/package/react-id-swiper#custom-build-swiper
This also adds a new screen to the dev menu to test carousels.
There are two ways to test this:
1. Run `yarn dev:storybook` and play with the Carousel stories
2. Run PirateShip web (`yarn ship:compile-web`), go to the develop menu, and then go to the Carousel sample screen
=> feat: update web carousel dependencies

yarn.lock
This bumps the version of tar being resolved for 4.x to 4.4.18 to fix a security issue.
=> feat: update tar version to fix security

packages/flagship/src/lib/rename.ts
We were unnecessarily forcing the path to lowercase when renaming packages. This would break on case sensitive filesystems if you had a capital letter in the path containing your project.
Fixes #1778
=> fix(flagship): stop forcing lowercasing when renaming packages

packages/fslinker/src/cache/global-cache.ts
The DefinitelyTyped definition of the global object for Node 16 removed NodeJS.Global as an exported type for the global object, which causes this file to fail to compile.
This change explicitly declares `__FLAGSHIP_LINKER_GLOBAL_CACHE__` as existing in the global scope so we can compile for Node 14 and 16.
=> fix(fslinker): update global typing to support node 16

packages/pirateship/package.json, yarn.lock
react-native-safe-area is not used in Flagship. This change removes the dependency.
=> chore(pirateship): remove unused react-native-safe-area

packages/fsapp/src/beta-app/router/history/history.web.ts
This handles an edge case of external navigations failing or the fsapp being left in memory.
It prevents the router from being stuck in thse cases
=> fix(fsapp): stuck router after external navigation

commitlint.config.js
This disables the body-max-line-length rule which seems to have enabled itself after upgrading to the latest version of commitlint.
=> chore: disable commitlint line length rule

package.json, yarn.lock
A number of dependencies (e.g., the Webpack build system and React Native) also depend on browserslist and we can't all update them. However, this will at least alleviate the security issue within Flagship.
=> chore: pin browserslist version

packages/fsengagement/src/carousel/RenderImageTextItem.tsx, packages/fsengagement/src/inboxblocks/IconTextBlock.tsx, packages/fsengagement/src/inboxblocks/ImageWithOverlay.tsx
Fixes some class components that are not able to use context directly so we have to inject context into them.  This applies the following prs that were made to develop: https://github.com/brandingbrand/flagship/pull/2252 and https://github.com/brandingbrand/flagship/pull/2255
=> fix(fsengagement): context fix for class components in v10

.gitignore
In this PR
========
Adds Vim's tmp files to git ignore so they are not accidentally committed.
=> chore: ignore vim's temporary files

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/__stories__/MultiCarousel.story.tsx, yarn.lock
In this PR
=========
Amends carousel behavior to snap back to first item when autoscrolling and reaches the end
Adds Storybook to demo the behavior
https://www.screencast.com/t/GM6UfK168m
=> fix: snaps carousel back to first image when autoscrolling

packages/fsapp/src/beta-app/development/version-overlay.component.tsx, packages/fsapp/src/beta-app/development/version-overlay.styles.tsx, packages/fsapp/src/beta-app/development/version-overlay.styles.web.tsx, packages/fsapp/src/beta-app/router/router.web.tsx, packages/fsapp/src/beta-app/shell.web/shell.context.tsx
Ticket: https://brandingbrand.atlassian.net/browse/FS-3176
This fixes some weird chrome specific rendering bugs with scroll views
This removes unneeded scroll views and uses `flexGrow` instead of `flex` for some other views
This uses `inset` instead of `height` to make the overlay cover the whole screen
=> fix(fsapp): FS-3176 - nested scrolling causing unpainted divs

package.json, yarn.lock
This adds a resolution to force the latest version of json-schema. This dependency is only used in dev tooling (Coveralls and Lerna) so we can safely use a package.json resolution for this update.
=> chore: manually bump json-schema versions

packages/fsapp/src/beta-app/router/history/history.ts
- This fixes an issue found recently on an app where if the user if able to tap/click the pop button multiple times, it then breaks any further navigation such as from categories.
- This simply returns if the navigation is out of range
**Testing**
In an Android simulator, navigate to a PIP
Click rapidly, twice on a pop trigger
Observe link triggers on categories always work now
=> fix(fsapp): return if out of range

.travis.yml, packages/flagship/android/build.gradle, packages/flagship/android/gradle/wrapper/gradle-wrapper.properties
[FCR-3189](https://brandingbrand.atlassian.net/browse/FCR-3189)
[FCR-3190](https://brandingbrand.atlassian.net/browse/FCR-3190)
- Fixing missed config issue in build.gradle templates
- Bumping gradle wrapper version to 4.2.0
- Updating gradle to 6.9.1
- 
1. Init pirateship
2. Navigate to the project android folder after init and generate a debugBuild -> `./gradlew assembleDebug`
3. Navigate to `app/build/outputs/apk/debug ` and verify .apk config is built to Android 12 API 31 with` aapt dump badging app-debug.apk `
```
package: name='com.brandingbrand.reactnative.and.pirateship' 
versionCode='10019000' 
versionName='10.19.0' 
platformBuildVersionName='12' 
platformBuildVersionCode='31' 
compileSdkVersion='31' 
compileSdkVersionCodename='12'
sdkVersion:'19'
targetSdkVersion:'31'
```
=> fix(flagship): updating android template files

packages/core/src/executors/init/platform/clean.ts, packages/core/src/executors/init/platform/index.ts
Built on https://github.com/brandingbrand/flagship/pull/2524.
The purpose for this PR was to remove the ios and android directories if they exist on init command which will fix a bug when a file already exists. We could change 2 lines of code to force overwriting but it increases build time and asset generation for ios gets corrupted.
=> fix(fs12): remove ios and android dirs init

apps/react-native/.kernelrc/env/env.prod.ts, packages/core/src/executors/init/platform/plist.ts, packages/core/src/index.ts, packages/core/src/types/ios/InfoPlist.ts, packages/core/src/types/ios/index.ts, packages/core/src/types/types.ts, packages/core/src/utils/ios/index.ts, packages/core/src/utils/ios/info-plist.ts, packages/core/src/utils/ios/plist.ts
Built on https://github.com/brandingbrand/flagship/pull/2525.
We want to encourage parsing parceable files over utilizing ejs for complex transformations. Ejs is good to use for simple plug-n-chug but not for complex assignments. This change adds functionality to parse plist files.
=> feat(fs12): info plist parser

package.json, yarn.lock
Turborepo rewrote their code from go -> rust in v1.8.0.
=> chore(fs12): bump turbo go -> rust

packages/plugin-permissions/src/types.ts, packages/plugin-permissions/test/index.test.ts
There are a lot of extraneous Android permissions, https://developer.android.com/reference/android/Manifest.permission, that aren't necessarily typed in https://github.com/zoontek/react-native-permissions/blob/master/src/permissions.android.ts - we support what is out-of-the-box from `react-native-permissions` since this is the purpose of the plugin. We extend the permissions type to accept any permission as well.
=> fix(fs12): extend android permissions with types

apps/react-native/package.json, package.json, yarn.lock
No additional changes: https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.70.8.
=> chore(fs12): react-native xcode 14.3 support

packages/core/assets/template/android/app/src/release/java/com/helloworld/ReactNativeFlipper.java, packages/core/src/executors/init/platform/packages.ts, packages/core/src/utils/path.ts
In React Native v0.71.* they moved conditionalizing ReactNativeFlipper from checking if it's debug to an abstraction class to the release directory which was missed during the upgrade process.
Added the packaged namespace'd `release` dir into the android template and updated the `packages` executor to update the package path.
N/a.
Run the example app and ensure the release dir has the proper namespace.
=> fix(core): android template release directory

.changeset/curly-glasses-sniff.md, .changeset/pre.json, apps/react-native/package.json, packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/assets/android/fastlane/Fastfile, packages/plugin-fastlane/package.json
Update the Fastfile for Android to have the task scoped to the app project 
this prevents it from trying to assemble react-native packages as libraries and just builds the app
[04bd401](https://github.com/NickBurkhartBB/flagship/commit/04bd4014265edc2d3d6e269942b02aac91f996b6)
Setup changeset for next alpha version
* init example project
* run fastfile assemble in Android project to verify app:assembleRelease task is run
=> fix(plugin-fastlane): scope assemble to app project

docs/src/pages/en/packages/plugins/fastlane/v2.0.1.mdx, packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/assets/ios/fastlane/Fastfile, packages/plugin-fastlane/package.json
Update ios compile lane in fastlane to skip code signing and archiving. The `xcargs` is no longer necessary.
=> feat(fastlane): update ios compile lane

apps/example/coderc/build/build.internal.ts, packages/cli-kit/__tests__/path.ts, packages/cli-kit/src/lib/path.ts, packages/cli/__tests__/app-delegate-mm.ts, packages/cli/__tests__/env-switcher-m.ts, packages/cli/src/transformers/ios/app-delegate-mm.ts, packages/cli/src/transformers/ios/index.ts
Adding `AppDelegate.mm` deep-linking delegate method.
Run the example app: `yarn flagship-code prebuild --build internal --env prod`. When the app has been installed to the simulator, close the app and run in the terminal: `xcrun simctl openurl booted "app://"` and verify app opens.
=> feat(code): add ios deep linking delegate

packages/jest-config/jest-preset.js, packages/jest-config/package.json, packages/jest-config/tsconfig.json
Update jest-preset.js to link to js files instead of ts files. When published you can only use js files. This will not interrupt the current monorepo workflow as cli and cli-kit are required to be built anyway before testing.
I created a packaged release via `npm pack`. I then utilized this *.tar in example app to test.
=> fix(code): jest-preset js

packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/assets/android/fastlane/Fastfile, packages/plugin-fastlane/package.json, packages/plugin-fastlane/test/index.test.ts
Android bundle lane in fastlane not incrementing build number. It was a missed conditional in the migration. Added additional test cases.
3. `yarn test`
=> fix(fastlane): increment android bundle build number

.changeset/silver-turtles-deny.md, packages/plugin-app-icon/package.json, yarn.lock
Audit and fix package vulnerabilities.
`yarn audit`
`npx yarn-audit-fix`
Additional vulnerabilities exist:
- `axios` which is a dependency of `fsapp`.
- `xml2js` which is a transitive dependency of `@leanplum/react-native-sdk`.
Only way to resolve these vulnerabilities is to do a resolution at root of the repo.
`yarn test`
=> chore(audit): apply audit fix vulnerabilities

.changeset/big-penguins-tease.md, packages/plugin-google-signin/package.json
Update `google-signin` plugin to support privacy manifest.
There is an additional patch that will be required: https://github.com/react-native-google-signin/google-signin/blob/cb1702e88317fbd79b85d229c1b57198c2d16bb0/RNGoogleSignin.podspec#L19 needs to be `7.1.0`.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5151)
`yarn test`
=> feat(google-signin): ENG-5151 update google-signin support for privacy manifest

.changeset/lemon-news-shave.md, packages/plugin-leanplum/package.json
Update `leanplum` plugin to support privacy manifest.
There is an additional patch that will be required: https://github.com/Leanplum/Leanplum-ReactNative-SDK/blob/5b6c59da18d781bf931959b3346c3e93cf02be80/react-native-leanplum.podspec#L22 needs to be `6.4.0`. There also must be a resolution: https://github.com/Leanplum/Leanplum-ReactNative-SDK/blob/5b6c59da18d781bf931959b3346c3e93cf02be80/package.json#L64 to override `clevertap-react-native` version to `^2.2.1`.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5151)
`yarn test`
=> feat(leanplum): ENG-5151 update leanplum support for privacy manifest

apps/docs/src/content/docs/guides/build.mdx, apps/docs/src/content/docs/packages/cli-kit.mdx, packages/cli-kit/__tests__/path.ts, packages/cli-kit/src/lib/path.ts, packages/cli-kit/src/schemas/build-config.ts, packages/cli/__tests__/app-entitlements.ts, packages/cli/__tests__/privacy-info-xcprivacy.ts, packages/cli/__tests__/privacy-info-xcprivacy_fixtures/PrivacyInfo.xcprivacy, packages/cli/src/transformers/ios/app-entitlements.ts, packages/cli/src/transformers/ios/index.ts, packages/cli/src/transformers/ios/privacy-info-xcprivacy.ts
The default provided PrivacyInfo.xcprivacy covers the basics for a React Native app w/ Flagship Code™. The ideal way for third-party SDKs to include their PrivacyInfo.xcprivacy is via their bundle linking via the podspec. Unfortunately some of these third-party SDKs are not maintained - we need a way to adding those required reasons via an override.
Now you can provide a path to a custom PrivacyInfo.xcprivacy that will override the default provided PrivacyInfo.xcrprivacy.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5152)
`yarn test`
=> feat(privacy-manifest): ENG-5152 allow custom privacy manifest

packages/cli/src/actions/env.ts
In release mode only bundle one env - equality test will look directly at file name rather than regex.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5157)
1. yarn install
2. yarn build
3. cd apps/example
4. yarn flagship-code prebuild --env prod --build internal --release
5. go to node_modules/@brandingbrand/fsapp/src/project_env_index.js
6. verify only one env
=> fix(env): ENG-5157 bundle only one env in release mode

.changeset/nine-numbers-design.md, packages/cli-kit/package.json, packages/cli/__tests__/project-pbxproj.ts, packages/cli/src/transformers/ios/project-pbxproj.ts, yarn.lock
The PR https://github.com/facebook/react-native/commit/520d120375c6b24bc161adea4f48d76537a34abc to add the PrivacyInfo.xcprivacy as a default file was not added correctly for Apple to recognize the manifest as part of the bundle. The PrivacyInfo.xcprivacy must be a PBXBuildFile and then added as resource file via PBXFileReference. If you go to the Build Phases -> Copy Bundle Resources the PrivacyInfo.xcprivacy will be listed there.
I have tested this with a separate app with 2 steps via beta testing:
1. Without PrivacyInfo.xcprivacy
2. With PrivacyInfo.xcprivacy
This resulted in errors for case 1 - and no errors for case 2.
Updated `xcode` library due to unsafe access of a `path` attribute https://github.com/apache/cordova-node-xcode/commit/e81ecabc18b0e43a1ae5457f16ebcbb8b0b62460. …
=> fix(privacy-manifest): ENG-5152 privacy manifest as pbxbuild resource

.changeset/strange-walls-wash.md, packages/plugin-fastlane/assets/android/fastlane/Fastfile, packages/plugin-fastlane/test/index.test.ts, yarn.lock
Android build number for is important for not only the Google Play Store but also if you are installing subsequent versions of a mobile application. The build number must be incremental compared to the previous version installed.
Adding the conditional to release mode to always increment the build number based on the previously released version.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5249)
`yarn test`
=> fix(fastlane): ENG-5249 android app center release mode

.changeset/poor-games-talk.md, apps/example/package.json, packages/cli/template/android/build.gradle, packages/cli/template/android/gradle.properties, yarn.lock
Android 14 support for Flagship Code™ v13.
It's advised against updating agp/kotlin versions outside of React Native updates: https://github.com/facebook/react-native/issues/36974#issuecomment-1516829016 and additionally it doesn't work either way as the gradle plugin was compiled with a specific kotlin version which will cause a mismatch compilation error.
The navigation library react-native-navigation must be minimally bumped to v7.37.2 for Android 14 support.
[Ticket]()
3. `yarn test`
4. Verify pass
5. `cd apps/example`
6. `yarn prebuild --build internal --env prod --platform android`
7. `yarn android`
8. Verify run
<details>
</details>
=> feat(adr): android 14 support

packages/cli-kit/src/lib/path.ts, packages/plugin-app-icon/package.json, packages/plugin-asset/package.json, packages/plugin-splash-screen/package.json, yarn.lock
Delay evaluation of project path - this was an issue with our internal template generation tool.
3. `yarn test`
4. `yarn flagship-code prebuild --build internal --env dev`
5. `yarn ios`
6. `yarn android`
7. Verify both apps run successfully
<details>
<summary>ios</summary>
</details>
<details>
</details>
=> fix(path): cache project path

.changeset/slimy-sloths-applaud.md, packages/cli/src/actions/env.ts
Env access is linked through `@brandingbrand/fsapp` with the `project_env_index.js` file. In fsapp v10 it's in the root directory whereas in v11 it's in the src directory. We need to conditionalize where we read that file from based on fsapp version.
Require the package.json of `@brandingbrand/fsapp` and determine which path we can use for the `project_env_index.js`.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5304)
3. `cd apps/example`
4. `yarn flagship-code prebuild --build internal --env prod`
5. Verify cli runs successfully
<details>
<summary>cli</summary>
</details>
=> feat(env): ENG-5304 support fsapp <11

.github/workflows/pr-test.yml, packages/cli/src/actions/info.ts, packages/cli/src/actions/packagers.ts, packages/cli/src/cmds/prebuild.tsx, packages/cli/src/components/Actions.tsx
Pause `react-ink` when `--verbose` option is enabled. Additionally, do not redirect stdout for exec commands.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5297)
3. `yarn test`
4. `cd apps/example`
5. `yarn flagship-code prebuild --build internal --env prod --verbose`
6. Verify verbosity
<details>
<summary>terminal</summary>
```sh
$ /Users/christopherherman/git/flagship/node_modules/.bin/flagship-code prebuild --build internal --env prod --verbose
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒                   ▒▒▒
▒▒                 ▒▒▒
▒▒               ▒▒▒
▒▒             ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒     ▒▒▒           ▒▒▒
▒▒   ▒▒▒           ▒▒▒
▒▒ ▒▒▒           ▒▒▒
▒▒▒▒           ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒ …
```
=> fix(cli): enable verbose option

.changeset/little-laws-play.md, apps/react-native/.coderc/env/env.dev.ts, apps/react-native/.coderc/env/env.prod.ts, apps/react-native/package.json, docs/src/pages/en/packages/core/v12.2.0.mdx, packages/core/assets/template/android/build.gradle, yarn.lock
Android 14 support.
It's advised against updating agp/kotlin versions outside of React Native updates: https://github.com/facebook/react-native/issues/36974#issuecomment-1516829016 and additionally it doesn't work either way as the gradle plugin was compiled with a specific kotlin version which will cause a mismatch compilation error.
The navigation library react-native-navigation must be minimally bumped to v7.37.2 for Android 14 support.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5275)
3. `yarn test`
4. Verify pass
5. `cd apps/react-native`
6. `yarn run init --platform android`
7. `yarn android`
8. Verify run
<details>
</details>
=> feat(adr): ENG-5275 android 14 support

.changeset/loud-fireants-battle.md, packages/cli/src/actions/env.ts
Update envs to default export: https://github.com/brandingbrand/flagship/blob/7b540442d2b83ad710e98981bd368039f0eb635c/packages/fsapp/src/index.ts#L6.
1. downgrade fsapp to v10
2. `yarn flagship-code prebuild --build internal --env prod`
3. verify project_env_index.js has default export envs
=> feat(cli): fsapp v10 env export default

packages/plugin-fastlane/package.json, packages/plugin-splash-screen/package.json, packages/plugin-target-extension/package.json
It's required to export any `@types` that are utilized within the plugins because they are un-compiled packages. When importing these types it imports them from source so the `@types` need to exist otherwise you will get a typescript error when running typescript compile.
1. `yarn test`
=> fix(plugins): expose @types

packages/cli-kit/src/@types/config.ts, packages/cli-kit/src/lib/guards.ts
It's not clear to the reasoning on why the type was being used the way it was. By conventional though it could be thought to do this a different way by setting a default value to the generic and conditionalizing it's value based on extending but when a generic value is not supplied in usage the generic value will be inferred thereby breaking the strict typing. Abstracting it and explaining it in a comment makes this more clear.
- `yarn test`
=> feat: abstract build config type

.changeset/fresh-days-chew.md, packages/cli-kit/__tests__/network-security-config-xml.ts, packages/cli-kit/__tests__/path.ts, packages/cli-kit/__tests__/xml.ts, packages/cli-kit/src/lib/path.ts, packages/cli-kit/src/parsers/xml.ts, packages/cli/__tests__/android-maniest-xml.ts, packages/cli/src/transformers/android/android-manifest-xml.ts, packages/cli/template/extras/android/app/src/main/res/xml/network_security_config.xml
When the network security configuration is added to the `AndroidManifest.xml` by default with an empty configuration it can interfere with the metro packager when developing.
Only update the `AndroidManifest.xml` with the network security configuration if someone utilizes the the parser. Note, the developer will be responsible for adding the local environments in non-release mode via their plugin.
- `yarn test`
=> fix(adr): disable network security config by default

packages/cli/package.json, packages/cli/src/actions/info.ts, yarn.lock
CLI text is not centered - use popular package `ansi-align` to center the CLI text.
- `yarn flagship-code prebuild --build internal --env prod`
<details>
<summary>cli</summary>
```
▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒                   ▒▒▒
▒▒                 ▒▒▒
▒▒               ▒▒▒
▒▒             ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒     ▒▒▒           ▒▒▒
▒▒   ▒▒▒           ▒▒▒
▒▒ ▒▒▒           ▒▒▒
▒▒▒▒           ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒       ▒▒▒
▒▒     ▒▒▒
▒▒   ▒▒▒
▒▒ ▒▒▒
▒▒▒▒
Flagship Code v13.0.0
Configurable - Extensible - Toolkit
```
</details>
=> fix: center cli text

.changeset/small-toys-argue.md, packages/plugin-permissions/__tests__/index.ts, packages/plugin-permissions/src/index.ts
In version 4.1.3 of react-native-permissions they changed the way they update their internal *.podspec file which our plugin does not accommodate for. To account for these changes - we will just execute the same ruby scripts that the documentation calls for.
- `yarn test`
- Run example app and verify camera permission works
<details>
<summary>ios</summary>
</details>
=> fix: plugin-permissions react-native-permissions versions

.changeset/angry-gifts-rescue.md, apps/example/package.json, packages/cli-kit/package.json, packages/cli/package.json, packages/plugin-app-icon/package.json, packages/plugin-asset/package.json, packages/plugin-fastlane/package.json, packages/plugin-native-navigation/package.json, packages/plugin-permissions/package.json, packages/plugin-splash-screen/package.json, packages/plugin-target-extension/package.json
Fix peer-dependency versions to match a semver range. We should limit internal dev dependencies with * to denote the latest available package in the workspace.
- `yarn test`
<details>
<summary>ios</summary>
</details>
<details>
</details>
=> fix: peer dependency versions

yarn.lock
Audit dependencies for vulnerabilities - we will continue to run this independently of dependabot until `develop` becomes the default branch.
Two dependencies cannot be upgrade correctly which are downstream dependencies of `@brandingbrand/fsapp`: `path-to-regexp` and `axios`.
<details>
<summary>audit</summary>
```
yarn audit v1.22.19
10 vulnerabilities found - Packages audited: 2051
Severity: 5 Moderate | 5 High
```
</details>
- https://github.com/brandingbrand/flagship/pull/2745
- https://github.com/brandingbrand/flagship/pull/2744
- https://github.com/brandingbrand/flagship/pull/2741
- `yarn test`
- Run example app
<details>
<summary>ios</summary>
</details>
<details>
</details>
=> chore: audit dependencies

apps/docs/src/content/docs/packages/plugin-fastlane.mdx, packages/plugin-fastlane/__tests__/index.ts, packages/plugin-fastlane/src/index.ts, packages/plugin-fastlane/src/types.ts, packages/plugin-fastlane/template/android/fastlane/Fastfile, packages/plugin-fastlane/template/android/fastlane/Pluginfile, packages/plugin-fastlane/template/ios/fastlane/Fastfile, packages/plugin-fastlane/template/ios/fastlane/Pluginfile
This PR updates the Fastlane plugin to optionally support a configuration for firebase app distribution.  If the config is provided the plugin will add the necessary lanes.  Besides including this configuration, the only other step for projects to integrate with FAD is to update their Github actions/workflows and to create a secret in their repo, GOOGLE_SERVICE_CREDENTIALS, which contains the firebase credentials for the google service account.
Overview of changes:
- Update Fastfile templates to provide conditional firebase lanes.
- Update Pluginfile templates to conditionally provide the necessary appcenter and/or firebase gems.
- Fastlane Pluginfiles templates are now rendered to account for conditional gem installations
- Updated tests
~~NOTE: I still need to verify Firebase Android …
=> ENG-5771: Add firebase app distribution support

.github/workflows/pr-test.yml
update the setup-ruby action version to work with latest ubuntu runner and not have it get picked up as self hosted runner
* verify test PR workflow after change
=> chore: update setup-ruby version in pr-test work flow

packages/cli/templates/react-native-0.72/addons/ios/Gemfile, packages/cli/templates/react-native-0.73/addons/ios/Gemfile
This pull request addresses a compatibility issue with the `concurrent-ruby` gem in the iOS continuous integration (CI) pipeline for React Native. The change ensures stability by pinning the `concurrent-ruby` gem to a version below `1.3.4`. This fix is applied to the `Gemfile` templates for React Native versions `0.72` and `0.73`.
N/A
To test this change:
1. Ensure that the `Gemfile` updates are reflected in the iOS CI pipeline configuration for React Native versions `0.72` and `0.73`.
2. Run the CI pipeline to verify that the `concurrent-ruby` gem version is successfully pinned and no longer causes errors.
3. Confirm that other gem dependencies are unaffected and that the pipeline completes successfully.
=> fix(gems): pin concurrent-ruby

.changeset/good-tips-occur.md, packages/cli-kit/src/lib/FlagshipCodeManager.ts
Add exit code when an action fails via the cli.
https://brandingbrand.atlassian.net/browse/ENG-6005
- `yarn test`
- malform the template podfile
- run the cli
- verify failure
```
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒                   ▒▒▒
▒▒                 ▒▒▒
▒▒               ▒▒▒
▒▒             ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒     ▒▒▒           ▒▒▒
▒▒   ▒▒▒           ▒▒▒
▒▒ ▒▒▒           ▒▒▒
▒▒▒▒           ▒▒▒
▒▒           ▒▒▒
▒▒         ▒▒▒
▒▒       ▒▒▒
▒▒     ▒▒▒
▒▒   ▒▒▒
▒▒ ▒▒▒
▒▒▒▒
Flagship Code v13.1.1
Configurable - Extensible - Toolkit
2025-01-22 12:10:20.454 info cli prebuild options
2025-01-22 12:10:20.455 info cli ├─ platform: "native"
2025-01-22 12:10:20.455 info cli ├─ logLevel: "info"
2025-01-22 …
```
=> fix(cli): ENG-6005 add exit code for failed actions

.changeset/itchy-readers-cover.md, apps/docs/src/content/docs/packages/plugin-fastlane.mdx, packages/plugin-fastlane/__tests__/index.ts, packages/plugin-fastlane/src/types.ts, packages/plugin-fastlane/template/android/fastlane/Fastfile, packages/plugin-fastlane/template/ios/fastlane/Fastfile
add new build option for firebase plugin to to reset build version to 1 if version mismatch during lane increment_build_firebase
default behavior on iOS is to reset if new version found
default behavior on Android is to just increment
* the easiest way might to do a npm pack of the package then install in an existing app
* run init and view fast lane files
* run fastlane increment_build_firebase and verify output
* modify build config to some different options and init again 
* view fast files and run fastlane increment_build_firebase and verify output
=> feat(plugin-fastlane): add option to reset build numbers in firebase inc build
