CONTRIBUTING.md
Remove instructions to include JIRA tickets in CONTRIBUTING.md
=> docs: remove instructions to include JIRA

packages/fsbazaarvoice/src/BazaarvoiceDataSource.ts, packages/fsbazaarvoice/src/BazaarvoiceReviewRequest.ts
Add BazaarvoiceReviewRequest type instead of using any
=> fix(fsbazaarvoice): add BazaarvoiceReviewRequest

packages/fscomponents/src/components/AddToCart.tsx
=> fix(fscomponents): add type to AddToCart swatchesProps

packages/flagship/__tests__/mock_project/android/app/build.gradle, packages/flagship/__tests__/mock_project/android/build.gradle, packages/flagship/android/app/build.gradle, packages/flagship/android/build.gradle, packages/flagship/android/gradle/wrapper/gradle-wrapper.properties
I removed the buildToolsVersion since the new version to gradle will use
the correct one.
=> chore(flagship): updates gradle to 4.4

packages/flagship/package.json, packages/fscomponents/src/components/ProductItem/components/ProductItemImage.tsx, packages/fsi18n/src/translations/en.ts, packages/pirateship/package.json, packages/pirateship/src/components/PSFilterActionBar.tsx, packages/pirateship/src/components/PSProductIndex.tsx, packages/pirateship/src/screens/Category.tsx, packages/pirateship/src/screens/ProductIndex.tsx, yarn.lock
Requires:
Implemented the following changes to the Product Index Page:
* Added number of products to the PIP title
* Impelemented new Filter button
* Implemented single and double column buttons using SVGs for easy re-coloring
=> feat(pirateship): redesigned sort and filter menu

packages/fsengage/README.md
reordered information, expanded each section with more explanation to give a clearer idea of overall workflow, and added table of contents.
=> docs(fsengage): expand analytics docs

packages/fsmockdatasources/src/commerce/mixins/ProductCatalog.ts
- Make "page" indexes start from one
- Derive page size from limit
- Calculate total products matching filters before applying pagination
=> fix(fsmockdatasources): Fix pagination

packages/fscomponents/src/components/SearchBar.tsx, packages/fscomponents/src/types/Store.ts
Allow for clearButtonMode to be set to value other than 'never' in SearchBar component.
Add ClearButtonMode type with options to types/Store.
=> feat(fscomponents): allow clearButtonMode in SearchBar

packages/pirateship/src/screens/Cart.tsx
from palette in ../styles/variables.ts
=> fix(pirateship): fix color of cart total line to primary green

packages/flagship/src/lib/link.ts
reverts #113 and #112 because it didn't work and causes more issues
=> fix: revert changes to link.ts script

packages/fsmockdatasources/src/commerce/mixins/ProductCatalog.ts
- Selected refinements were not included in the response
- Multiple refinement values for the same key did not work as expected
=> fix(fsmockdatasources): Fix handling of refinements

packages/fsapp/package.json, packages/pirateship/package.json, yarn.lock
Update https://github.com/brandingbrand/flagship/pull/81 to address conflicts
=> chore: update react-native-device-info to 0.22.0

packages/pirateship/src/screens/Shop.tsx
- replaced PSButton with TouchableOpacity wrapper to avoid flashing green on touch
- aligned 'View All' text and right arrow vertically with 'Shop All Categories'
- matched font size of 'View All' with 'Shop All Categories'
=> fix(pirateship): fix view all alignment & green color on touch

packages/fscomponents/src/components/Button.tsx
Make the disabled prop in Button disable the component's TouchableHighlight element.
=> fix(fscomponents): Implement button disabling

packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/pirateship/src/components/PSProductCarousel.tsx, packages/pirateship/src/components/PSScreenWrapper.tsx, packages/pirateship/src/screens/Shop.tsx
new PR for https://github.com/brandingbrand/flagship/pull/130
=> fix(pirateship): fixes #130 text color on shop screen

packages/flagship/package.json, packages/fscontinuousdeployment/package.json, yarn.lock
=> chore: update request to version 2.88.0

packages/flagship/package.json, yarn.lock
=> chore: update @types/yargs to version 11.1.1

packages/fsweb/package.json, yarn.lock
=> chore: update webpack to version 4.16.5

packages/fsbazaarvoice/src/BazaarvoiceDataSource.ts
Reivew IDs in the Filter parameter were being serialized incorrectly. The attribute id was repeated
for each sku when there should have been a single attribute id with comma-delimited values.
=> fix(fsbazaarvoice): Fix serialization of review ids in request

packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/MainApplication.java, packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/ThreadSafeUIImplementation.java, packages/fsapp/package.json, packages/fsshopify/package.json, yarn.lock
* Fix unsafe UIImplementation threading
=> fix(flagship): Fix unsafe UIImplementation threading

packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/MainApplication.java
This throws an error when compiling Android.
=> fix(flagship): remove unneeded override from mainapplication

packages/fscomponents/package.json
=> fix: update memoize-one to version 4.0.2

packages/flagship/package.json, packages/fscomponents/package.json, packages/pirateship/package.json
=>  fix: update react-native-svg to version 7.0.2

commitlint.config.js, lerna.json, package.json, yarn.lock
- Update Lerna to version 3.4
- Update commitlint to version 7.1.2 to support Lerna 3.4
Closes #148
=> chore: update Lerna to 3.4

commitlint.config.js
Add release as an allowed conventional commit scope
=> chore: add release conventional commit scope

lerna.json
Add version number to default publish commit message
=> chore: add version to publish commit message

packages/fscheckout/src/index.tsx
Expose the StepTracker component so that a custom renderStepTracker function may use it.
=> refactor(fscheckout): Export StepTracker component

packages/fscomponents/src/components/Grid.tsx
So it can be called programatically.
=> fix: Make scrollToTop function public

packages/fscomponents/src/components/SearchBar.tsx
#Description 
Add of 'shouldClearOnSubmit' for clearing the input searchbar after submiting.
=> feat(fscomponents): searchbar prop if input should clear after submit

packages/fslocator/src/components/LocatorContainer.tsx
add functions for address and location not found
=> feat(fslocator): add custom error handling

packages/fslocator/src/components/LocatorContainer.tsx, packages/fslocator/src/components/LocatorList.tsx, packages/fslocator/src/components/LocatorMapVertical.tsx, packages/fslocator/src/components/MapView.tsx, packages/fslocator/src/components/MapView.web.tsx
add default region to fslocator
=> feat(fslocator): add default region prop

packages/fsengage/src/modules/analytics/providers/leanplum/LeanplumProvider.ts, packages/fsengage/src/typings.d.ts
This fixes the LeanplumProvider typings so storybook build works.
=> fix(fsengage): fix leanplum typings for storybook

packages/flagship/ios/FLAGSHIP.xcodeproj/project.pbxproj
This updates all instances of IPHONEOS_DEPLOYMENT_TARGET in project.pbxproj to use 10.3.
=> fix(flagship): update iphoneos deployment target to 10.3

packages/fscomponents/src/components/SearchBar.tsx
adds cancel button style props and a render cancel button prop to the search bar in fscomponents
=> feat(fscomponents): increase customizability of search bar

package.json, packages/fsapp/package.json, packages/pirateship/package.json, yarn.lock
=> chore(flagship): upgrade react redux to 6.0

package.json, packages/fsapp/package.json, packages/pirateship/package.json, yarn.lock
Reverts brandingbrand/flagship#370 - this possibly introduced breaking changes
=> chore: revert pr #370

packages/fscomponents/src/components/ReviewIndicator.tsx
added optional accessiblitylabel and optional color for empty stars
=> fix(fscomponents): add opt prop and color change for reviewIndicator

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx
-add accessibility to multicarousel pagination
=> refactor(fscomponents): multicarousel pagination

packages/pirateship/src/components/PSHTMLView.tsx
Testable in pirateship product detail screen:
=> refactor(pirateship): pshtmlview to stateless function component

packages/pirateship/src/components/PSFilterActionBar.tsx
...testable in pirateship package, product index > filter.
=> refactor(pirateship): psfilteractionbar to stateless function component

packages/flagship/package.json, packages/fsapp/package.json, packages/fsbazaarvoice/package.json, packages/fsbrandcmsproductcatalog/package.json, packages/fscart/package.json, packages/fscategory/package.json, packages/fscheckout/package.json, packages/fscodestyle/package.json, packages/fscommerce/package.json, packages/fscomponents/package.json, packages/fscontinuousdeployment/package.json, packages/fsengage/package.json, packages/fsengagement/package.json, packages/fsfoundation/package.json, packages/fsi18n/package.json, packages/fslocator/package.json, packages/fsmockdatasources/package.json, packages/fsnetwork/package.json, packages/fspowerreviews/package.json, packages/fsproductdetail/package.json, packages/fsproductindex/package.json, packages/fssalesforce/package.json, packages/fsshopify/package.json, packages/fstestproject/package.json, packages/fsturnto/package.json, packages/fsups/package.json, packages/fsweb/package.json, packages/pirateship/package.json
adds `"sideEffects": false,` to each **package.json** in packages directory
=> chore(flagship): block side effects for tree shake

packages/pirateship/src/components/PSRow.tsx
=> refactor(pirateship): psrow to stateless function component

packages/fscomponents/src/components/ShareButton/ShareButton.tsx, packages/fscomponents/src/components/ShareButton/ShareButtonProps.ts, packages/pirateship/src/components/PSProductDetail.tsx, packages/pirateship/src/screens/ProductDetail.tsx
converted to stateless function component, testable  in pirateship PDP:
=> refactor(fscomponents): sharebutton to sfc

packages/fsapp/package.json, yarn.lock
No breaking changes: https://github.com/avishayil/react-native-restart/releases
=> chore(fsapp): upgrade react-native-restart

package.json, yarn.lock
DefinitelyTyped, no breaking changes
=> chore(flagship): upgrade @types/memoize_up to ^4.1.1

packages/fssalesforce/package.json, yarn.lock
=> chore(fssalesforce): upgr dtsgen to 2.0.6

packages/fscomponents/src/components/Button.tsx, packages/fscomponents/src/components/Swatch.tsx
This adds accessibilityRole to the button component and accessibilityRole+accessibilityLabel to the swatch component.
=> feat(fscomponents): add accessibility labels to button and swatches

packages/fscomponents/src/components/CategoryBox.tsx, packages/fscomponents/src/components/SearchBar.tsx
This adds accessibilityRole to the CategoryBox and SearchBar components.
=> feat(fscomponents): add accessibility role to categorybox and searchbar

packages/fscomponents/src/components/Carousel/Carousel.tsx, packages/fscomponents/src/components/Carousel/CarouselProps.ts
This changes add button related properties in react-native-swiper to Carousel component. Including showsbutton, nextButton and prevButton.
=> feat(fscomponents): add button properties for carousel

packages/fscomponents/src/components/Step.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
This changes add completed state accessibility label for Step component.
=> feat(fscomponents): add completed state accessibility label for Step

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, yarn.lock
<MultiCarousel> now accepts 4 new style props to allow styling of the next/prev arrows
`nextArrowContainer`
`nextArrow`
`prevArrowContainer` and
`prevArrow`
=> feat(fscomponents): add ability to pass arrow styles for multicarousel

packages/fsengage/src/modules/cms/ContentManagementSystem.ts, packages/fsengage/src/modules/cms/providers/ContentManagementSystemProvider.ts, packages/fsengage/src/modules/cms/providers/core/CoreContentManagementSystemProvider.ts
This allows for fetching CMS content by group.
=> feat(fsengage): allow fetching content for group

packages/fsengagement/package.json, packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/inboxblocks/FullScreenImageCard.tsx, packages/fsengagement/src/inboxblocks/RecipeBlock.tsx, packages/fsengagement/src/inboxblocks/index.tsx, packages/fsengagement/src/index.ts, packages/fsengagement/src/types.ts, yarn.lock
@bweissbart 
- add new `FullScreenImageCard` for title cards
- add new carousel option for title cards (instead of default list view)
=> feat(fsengagement): add new carousel option and full screen background

package.json, yarn.lock
This should resolve an issue we're seeing in CI as described here: https://github.com/react-native-community/cli/issues/586
=> chore: update react native cli dependency to 1.11.2

packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts
added and implemented the following optional props:
* hideZoomButton
* A bool to show/hide zoom functionality
* containerStyle
* StyleProp to ensure that all wrapping elements are styled as desired
* renderImageWeb
* A function that returns a react node
=> feat(fscomponents): add some option props to zoomCarousel

packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/components/ZoomCarousel/types.ts
added and implemented the following optional props:
* hideZoomButton
* A bool to show/hide zoom functionality
* containerStyle
* StyleProp to ensure that all wrapping elements are styled as desired
* renderImageWeb
* A function that returns a react node
=>  feat(fscomponents): add some option props to zoomCarousel

packages/fsweb/webpack.config.js, packages/pirateship/package.json, packages/pirateship/scripts/buildWebDemo.sh
Also fixes building the web demo.
I was able to build the storybook (build and dev) and web demo with these changes, along with running ship:compile-web.
=> fix(fsweb): Update the webpack config file

packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/inboxblocks/ShopIngredientsBlock.tsx, packages/fsengagement/src/inboxblocks/index.tsx
- allow for new shop ingredients button
- programmatically creates deep link with product IDs
- pass story down into cta zones
=> feat(fsengagement): add shoppable ingredients cta

packages/fscomponents/src/components/ReviewItem.tsx, packages/fscomponents/src/styles/ReviewItem.ts, packages/fsi18n/src/translations/en.ts
There were some bugs with the syndication badges on smaller devices. Fixed them with flex-wrap. Also updated copy.
=> feat: update bv syndicated indicator style

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx
=> fix: excessive calls of handleContainerSizeChange in MultiCarousel

packages/flagship/src/commands/init.ts, packages/flagship/src/lib/ios.ts, packages/flagship/src/types.ts
Improvement for the iOS configuration project
Update the info.plist so it accept background modes capabilities
=> feat(flagship): support background modes

packages/fscomponents/src/components/ReviewItem.tsx, packages/fscomponents/src/components/SyndicationIndicator.tsx
fix: fix infinite re-render bug when using renderSyndicatedIndicator prop
=> fix: fix infinite re-render bug when using renderSyndicatedIndicator prop

packages/fscomponents/src/components/ModalHalfScreen.tsx
#309
This PR was closed because it was old and had conflicts.
#517
Let's take what David did and create a fresh PR.
=> feat: add position property for half modal component

packages/flagship/src/commands/init.ts, packages/flagship/src/lib/__tests__/cocoapods.test.ts, packages/flagship/src/lib/cocoapods.ts, packages/flagship/src/lib/modules/ios/react-native-adobe-analytics.ts, packages/flagship/src/lib/modules/ios/react-native-firebase.ts, packages/flagship/src/lib/modules/ios/react-native-leanplum.ts, packages/flagship/src/types.ts
This PR add support to add new dependencies to the configuration object and modify the podfile in the init script.
=> fix(flagship): add support for new pods

packages/fsweb/package.json, packages/fsweb/webpack.config.js, yarn.lock
Resolve issue #241
Changed deprecated webpack server to new webpack dev server.
=> build: upgrade deprecated webpack dev server

package.json, yarn.lock
Update react-dom library for #397
=> chore: update react-dom library

packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/inboxblocks/CTABlock.tsx, packages/fsengagement/src/inboxblocks/FullScreenImageCard.tsx, packages/fsengagement/src/inboxblocks/TabbedStoryItem.tsx, packages/fsengagement/src/inboxblocks/TextBlock.tsx
Adds optional language localization
=> feat(fsengagement): add language localization

packages/fscomponents/src/components/ModalHalfScreen.tsx
This fixes the half screen window height in dimensions listener and also removes the listener when unmount.
=> fix(fscomponents): ModalHalfScreen listener height update

packages/fscomponents/src/components/ImageWithOverlay.tsx
**https://jira.brandingbrand.com/browse/FLAGSHIP-52**
**Description:**
1) wrap ImageWithOverlay with React.memo()
=> chore(fscomponents): memoize ImageWithOverlay.tsx

packages/fscomponents/src/components/Loading.tsx
**https://jira.brandingbrand.com/browse/FLAGSHIP-53**
**Description:** 
1. Converted Loading.tsx from to a Functional Component
=> chore(fscomponents): convert Loading.tsx to functional component

packages/fscomponents/src/components/CategoryLine.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-51
- Update CategoryLine to functional component with memo
- run fs test
=> refactor(fscomponents): FLAGSHIP-51 Updating To Function Component

packages/fscomponents/src/components/NavArrow.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-55
- Update NavArrow to function component using memo
- run fs test
=> refactor(fscomponents): FLAGSHIP-55 Updating To Function Component

packages/fscomponents/src/components/PageIndicator.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-56
- Change PageIndicator to function component using memo
- run fs test
=> refactor(fscomponents): FLAGSHIP-56 Updating To Function Component

packages/fscomponents/src/components/CategoryBox.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-50
CategoryBox used to be a pure component. This PR is to update it to a function component with react memo.
1. run `yarn && yarn build:storybook && yarn dev:storybook`
2. navigate to *Category* and then *CategoryBox*
=> refactor(fscomponents): FLAGSHIP-50 Make CategoryBox a function component

packages/fscomponents/src/components/ReviewIndicator.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-60
- Update ReviewIndicator to function component
- run fs test
=> refactor(fscomponents): FLAGSHIP-60 Updating To Function Component

packages/fstestproject/babel.config.js, packages/fstestproject/metro.config.js, packages/fstestproject/package.json, packages/fstestproject/scripts/buildWebDemo.sh, packages/fstestproject/scripts/buildiOS.sh, packages/fstestproject/scripts/fixRNLink.js, packages/fstestproject/scripts/getDependencyConfig.js, tsconfig/tsconfig.build.json, yarn.lock
Added up-to-date metro and babel configs and missing dependencies so the test project works. To run: yarn testproject:init && yarn testproject:run-ios
=> chore(fstestproject): get test project working again

packages/fscomponents/src/components/RefineActionBar.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-59
- Convert RefineActionBar into function component
- run fs test
=> refactor(fscomponents): FLAGSHIP-59 Updating To Function Component

packages/fscomponents/src/components/ProductMetadata.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-58
- Update ProductMetadata to function component
- run fs test builds
**I couldnt get the test project to compile so this was only tested with storybook**
=> refactor(fscomponents): FLAGSHIP-58 Updating To Function Component

packages/fscomponents/src/components/Step.tsx
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-65
- update Steps to function component
- run fs test
=> refactor(fscomponents): FLAGSHIP-65 Updating To Function Component

packages/fscomponents/src/components/TouchableOpacityLink.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-73
TouchableOpacityLink used to be a class-based component. This PR is to update it to a function component.
1. run `yarn && yarn build:storybook && yarn dev:storybook`
2. navigate to *TouchableOpacityLink* and then *basic usage*
=> refactor(fscomponents): FLAGSHIP-73 Update to a function component

packages/fscomponents/src/components/StepIndicator.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-66
Updating StepIndicator to a function component
1. run ```yarn && yarn build:storybook && yarn dev:storybook```
2. navigate to StepIndicator and then basic usage
=> refactor(fscomponents): FLAGSHIP-66 Updating to function component

packages/fscomponents/src/styles/ReviewIndicator.ts
This replace fontFamily: "Arial" in ReviewIndicator stylesheet with fontFamily: "sans-serif".
=> fix(fscomponents): replace Arial with sans-serif

packages/fscomponents/src/components/TouchableHighlightLink.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-72
update `TouchableHighlightLink` to a function component
=> refactor(fscomponents): FLAGSHIP-72 Update to a function component

packages/fscomponents/src/components/TouchableWithoutFeedbackLink.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-74
Updating TouchableWithoutFeedbackLink to a function component
Had to create a TouchableWithoutFeedbackLink storybook component and validate it behaved as expected
=> refactor(fscomponents): FLAGSHIP-74 Updating to function component

packages/fscomponents/src/components/ReviewItem.tsx, packages/fscomponents/src/components/SyndicationIndicator.tsx
https://jira.brandingbrand.com/browse/FLAGSHIP-67
Updating SyndicationIndicator to a function component.
Had to create a SyndicationIndicator storybook component and validate it behaved as expected. Had to also use a default image (just grabbed search).
=> refactor(fscomponents): FLAGSHIP-67 Update to function component

packages/fscomponents/src/components/ApplePayButton/ApplePayButton.ios.tsx, packages/fscomponents/src/components/ApplePayButton/ApplePayButton.web.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-101
- add ada to ApplePay button component
- run fs test
- confirm with screen reader
=> refactor(fscomponents): FLAGSHIP-101 Adding Accessibility To Component

packages/fscomponents/src/components/Accordion.tsx
**Ticket:** https://jira.brandingbrand.com/browse/FLAGSHIP-105
- add ada to ShareButton component
- run fs test
- confirm with screen reader
=> refactor(fscomponents): FLAGSHIP-105 Adding Accessibility To Component

packages/fscomponents/src/components/Alert.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-88
- add translations to alert.tsx
- run fs tests
=> refactor(fscomponents): FLAGSHIP-88 Add translations to alert

packages/fscomponents/src/components/CreditCardForm.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-91
- Add translations to CreditCardForm.tsx
- run fs tests
=> refactor(fscomponents): FLAGSHIP-91 update with translations

packages/fscomponents/src/components/FilterList/FilterListDrilldown.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-85
- add translations to filterlistdrilldown
- run fs tests
=> refactor(fscomponents): FLAGSHIP-85 update with translations

packages/fscomponents/src/components/FilterList/FilterList.tsx, packages/fscomponents/src/components/FilterList/FilterListDrilldown.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-85
- add translations to filterlistdrilldown
- run fs tests
=> refactor(fscomponents): FLAGSHIP-86 update with translations

packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
=> feat(fscomponents): FLAGSHIP-104 accessibility for Zoom carousel

packages/fscomponents/package.json, packages/fscomponents/src/components/FormikFields/TextField.tsx, packages/fscomponents/src/components/PromoFormFK.tsx, packages/fscomponents/src/components/__stories__/PromoFormFK.story.tsx, packages/fscomponents/src/components/index.ts, packages/fscomponents/src/lib/formikHelpers.ts, packages/fscomponents/src/lib/translations/index.ts, packages/fscomponents/src/styles/FormFK.ts, packages/fscomponents/src/styles/PromoFromFK.ts, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts, yarn.lock
Notes:
- Implement PromoForm with Formik
=> feat(fscomponents): Add to fscomponents and PromoForm

packages/fscomponents/src/components/PayPalCheckoutButton.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-96
- add translations to Selector
- run fs tests
=> refactor(fscomponents): FLAGSHIP-96 Add Translation To Component

packages/fscomponents/src/components/MoreText.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-95
- add translations to Selector
- run fs tests
=> refactor(fscomponents): FLAGSHIP-95 Add Translation To Component

packages/fscomponents/src/components/__stories__/FilterList.story.tsx, packages/fscomponents/src/components/__stories__/FilterListDrilldown.story.tsx, packages/fscomponents/src/components/__stories__/Form.story.tsx, packages/fscomponents/src/components/__stories__/MultiCarousel.story.tsx
Them being in different folders was making them load in unpredictable orders, so they were no longer alphabetized.
=> fix(fscomponents): Move story files to all live in the same folder

packages/fscomponents/src/components/PromoForm.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-97
- add translations to PromoForm component
- run fs tests
=> refactor(fscomponents): FLAGSHIP-97 Add Translations To Component

packages/fscomponents/src/components/AddressForm.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-89
- add translations to AddressForm component
- run fs tests
=> refactor(fscomponents): FLAGSHIP-89 Add Translations To Component

packages/fscomponents/src/components/ReviewIndicator.tsx, packages/fsi18n/src/translations/en.ts, packages/fsi18n/src/types.ts
**Ticket:**
- https://jira.brandingbrand.com/browse/FLAGSHIP-98
- Add translation support to reviewindicator
- run fs tests
=> refactor(fscomponents): FLAGSHIP-98 Add Translations To Component

packages/fsi18n/src/i18nHelper.ts, packages/fsi18n/src/types.ts
=> fix(fsi18n): Add set locale to fsi8n

packages/fsshopify/src/mixins/ShopifyCartDataSource.ts, packages/pirateship/src/screens/DesktopPassthrough.tsx
This allows storybook to run by fixing typing issues that arose in a couple files due to differences between RN and web APIs.
=> chore: fix type conflicts for storybook

packages/fscomponents/src/components/__stories__/CartItem.story.tsx
CartItem story has been added to the storybook
=> feat: add story to cartItem component

packages/fscomponents/src/components/__stories__/CreditCardNumber.story.tsx
CreditCardNumber story has been added to the storybook
=> feat: Create CreditCardNumber story

packages/fscomponents/src/components/__stories__/PageIndicator.story.tsx
PageIndicator story has been added to the storybook
=> feat: add story to PageIndicator component

packages/fscomponents/src/components/PayPalCheckoutButton.tsx, packages/fscomponents/src/components/__stories__/PayPalCheckoutButton.story.tsx
PayPalCheckoutButton story has been added to the storybook
=> feat: add story to PayPalCheckoutButton component

packages/fscomponents/src/components/__stories__/Accordion.story.tsx
- Added knobs to all accordian stories
**Testing**
- Pull down, `yarn run dev:storybook`
- Interact with knobs in each accordian story
=> feat(fscomponents): add knobs to accordian stories

packages/fscomponents/src/components/Carousel/CarouselProps.ts
create serializable props for carousel component
=> feat: add serializable props to carousel component

packages/fscomponents/src/components/CartCount.tsx
Create serializable props interface for CartCount component.
=> feat: add serializable props to CartCount component

packages/fscomponents/src/components/CategoryLine.tsx
Create serializable props interface for CategoryLine component
=> feat: add serializable props for CategoryLine component

packages/fscomponents/src/components/Alert.tsx
Create serializable props interface for Alert component.
=> feat: add serializable props to Alert component

packages/fscomponents/src/components/CategoryBox.tsx
Create serializable props interface for CategoryBox component
=> feat: add serializable props for CategoryBox component

packages/fscomponents/src/components/Swatches.tsx
Add serializable props for Swatches component
=> feat: add serializable props for swatches

packages/fscomponents/src/components/Stepper.tsx
Add serializable props for Stepper component.
=> feat: add serializable props to Stepper component

packages/fscomponents/src/components/StatelessStepper.tsx
Create serializable props interface for StatelessStepper component
=> feat: add serializable props for StatelessStepper component

packages/fscomponents/src/components/Step.tsx, packages/fscomponents/src/components/StepIndicator.tsx
Create serializable props interface for Step and StepIndicator components
=> feat: add serializable props for Step and StepIndicator

packages/fscomponents/src/components/SearchScreen.tsx
Add serializable props for SearchScreen component.
=> feat: add serializable props to SearchScreen component

packages/fscomponents/src/components/SearchModal.tsx
Create serializable props interface for SearchModal component
=> feat: add serializable props to SearchModal Form component

packages/fscomponents/src/components/MoreText.tsx
Create serializable props interface for MoreText component
=> feat: add serializable props for MoreText component

packages/fscomponents/src/components/ReviewsSummary.tsx
Create serializable props interface for ReviewsSummary component
=> feat: add serializable props for ReviewsSummary

packages/fscomponents/src/components/ReviewsList.tsx
Create serializable props interface for ReviewsList component
=> feat: add serializable props for ReviewsList

packages/fscommerce/src/index.ts
[ticket](https://brandingbrand.atlassian.net/browse/FS-395?jql=project%20%3D%20FS%20AND%20resolution%20%3D%20Unresolved%20AND%20assignee%20in%20(557058%3A145408bc-f00c-4b29-9e58-aac49aa04404)%20ORDER%20BY%20priority%20DESC)
=> chore(fscommerce): FS-395 expose AuthType enum

packages/fscomponents/src/components/ProductItem/components/ProductItemImage.tsx
Replace all occurrences of "any" in fscomponents/ProductItem
=> feat: Replace all occurrences of "any" in fscomponents/ProductItem

packages/pirateship/src/components/PSCartItem.tsx
=> feat: replace all any in PSCartItem

packages/pirateship/src/components/PageDots.tsx
Replace all occurrences of "any" in PageDots
=> feat(any-occurrences): Replace all occurrences of "any" in PageDots

packages/fsapp/src/lib/nav-wrapper.ts, packages/fsapp/src/lib/nav-wrapper.web.tsx, packages/fsapp/src/lib/push-route.ts, packages/fsapp/src/types/index.ts
Adds the updateProps functionality for both web and native: https://wix.github.io/react-native-navigation/api/component/#updateprops
=> feat(fsapp): Add updateProps to navigator

packages/fsengagement/src/EngagementService.ts
add two new methods
- `getSegments` gets a list of segments for an app and optionally returns a list of specified attributes that match the rule for the segment
- `getInboxBySegment` fetches the inbox for a particular segment
=> feat(fsengagement): new methods to return segment list and messages

package-lock.json, packages/pirateship/src/components/PSFilterActionBar.tsx, packages/pirateship/src/components/PSRow.tsx, packages/pirateship/src/components/PSShopLandingCategories.tsx
- Removing the return statement in the render image function seems to remove the black boxes and render the proper arrows
=> fix(pirateship): svg arrows no longer black boxes

packages/fsengagement/src/EngagementComp.tsx, packages/fsengagement/src/EngagementProductModal.tsx, packages/fsengagement/src/WebView.tsx, packages/fsengagement/src/carousel/RenderDemoProduct.tsx, packages/fsengagement/src/inboxblocks/FeaturedTopCard.tsx, packages/fsengagement/src/types.ts
Make sure navigators are properly set, clear out unused props, and update showModal functions.
=> fix(fsengagement): Update engagement for Navigator updates

packages/flagship/ios/Podfile, packages/flagship/src/lib/fs.ts
Our logic to add pods was broken because we removed the identifying line
Readded line for Podfile updates
Also updated logic for fs.update to use doesKeywordExist function to find other issues
This will allow us to better audit script logic in the future and find potential breaking changes sooner
=> fix(flagship): iOS Pods not being added

package.json, packages/flagship/android/app/build.gradle, packages/flagship/android/app/src/main/java/com/brandingbrand/reactnative/and/flagship/MainApplication.java, packages/flagship/android/build.gradle, packages/flagship/android/settings.gradle, packages/fsapp/package.json, packages/fsengagement/package.json, packages/fstestproject/package.json, packages/pirateship/package.json, yarn.lock
Fixes issues with tab bar icons not showing up in iOS 14.
BREAKING CHANGES: (should not affect most cases)
https://github.com/wix/react-native-navigation/blob/master/CHANGELOG.md#breaking-changes
=> fix(flagship): Upgrade to react-native-navigation 6

packages/fscomponents/src/components/ReviewIndicator.tsx
Replace all occurrences of "any" in ReviewIndicator
=> feat(fscomponents): Replace all occurrences of "any" in ReviewIndicator

packages/fscomponents/src/components/Swatches.tsx
Replace all occurrences of "any" in Swatches
=> feat(any-occurrences): Replace all occurrences of "any" in Swatches

packages/fscomponents/src/components/SearchBar.tsx
Replace all occurrences of "any" in SearchBar
=> feat(fscomponents): Replace all occurrences of "any" in SearchBar

packages/fscomponents/src/components/Grid.tsx
Replace all occurrences of "any" in Grid
=> feat(any-occurrences): Replace all occurrences of "any" in Grid

packages/fscomponents/src/components/PromoForm.tsx
Replace all occurrences of "any" in PromoForm component
=> feat(fscomponents): Replace all occurrences of "any" in PromoForm component

packages/fscomponents/src/components/CreditCardForm.tsx
Replace all occurrences of "any" in CreditCardForm component
=> feat(fscomponents): Replace all occurrences of "any" in CreditCardForm component

packages/fscomponents/src/components/SyndicationIndicator.tsx
Replace all occurrences of "any" in SyndicationIndicator
=> feat(fscomponents): replace all occurrences of "any" in SyndicationIndicator

packages/fscomponents/src/components/SearchModal.tsx
Replace all occurrences of "any" in SearchModal
=> feat(fscomponents): Replace all occurrences of "any" in SearchModal

packages/fscomponents/src/components/AddressForm.tsx
Replace all occurrences of "any" in AddressForm
=> feat(fscomponents): Replace all occurrences of "any" in AddressForm

packages/fsnetwork/src/index.ts
Replace all occurrences of "any" in FSNetwork package
=> feat(fsnetwork): Replace all occurrences of "any" in FSNetwork package

packages/fscomponents/src/components/Selector/Selector.tsx, packages/fscomponents/src/components/Selector/SelectorList.tsx
Replace all occurrences of "any" in fscomponents/Selector
=> feat: Replace all occurrences of "any" in fscomponents/Selector

packages/pirateship/src/components/PSScreenWrapper.tsx
Replace all occurrences of "any" in PSScreenWrapper
=> feat: Replace all occurrences of "any" in PSScreenWrapper

packages/pirateship/src/components/PSHeroCarousel.tsx
Replace all occurrences of "any" in PSHeroCarousel
=> feat(pirateship): Replace all occurrences of "any" in PSHeroCarousel

packages/pirateship/src/components/PSLabeledValues.tsx
Replace all occurrences of "any" in PSLabeledValues
=> feat(pirateship): Replace all occurrences of "any" in PSLabeledValues

packages/pirateship/src/components/PSPlaceholder.tsx
Replace all occurrences of "any" in PSPlaceholder
=> feat(pirateship): Replace all occurrences of "any" in PSPlaceholder

packages/pirateship/src/components/PSTotals.tsx
Replace all occurrences of "any" in PSTotals
=> feat(any-occurrences): Replace all occurrences of "any" in PSTotals

packages/fscomponents/src/components/ProductMetadata.tsx
Replace all occurrences of "any" in fscomponents/ProductMetadata
=> feat: Replace all occurrences of "any" in fscomponents/ProductMetadata

packages/fscomponents/src/components/CMSFeedback.tsx
Replace all occurrences of "any" in fscomponents/CMSFeedback
=> feat: Replace all occurrences of "any" in fscomponents/CMSFeedback

packages/fscomponents/src/components/CMSProvider.tsx
Replace all occurrences of "any" in CMSProvider component
=> feat(fscomponents): Replace all occurrences of "any" in CMSProvider component

packages/fscomponents/src/components/Alert.web.tsx
Replace all occurrences of "any" in fscomponents/Alert.web
=> feat: Replace all occurrences of "any" in fscomponents/Alert.web

packages/fscomponents/src/components/ActionBar.tsx
Replace all occurrences of "any" in ActionBar
=> feat(fscomponents): Replace all occurrences of "any" in ActionBar

packages/fscomponents/src/components/Alert.tsx
Replace all occurrences of "any" in Alert
=> feat(fscomponents): replace all occurrences of "any" in Alert

packages/fscomponents/src/components/SearchScreen.tsx
Replace all occurrences of "any" in SearchScreen
=> feat(fscomponents): Replace all occurrences of "any" in SearchScreen

packages/fscomponents/src/components/ModalHalfScreen.tsx
Replace all occurrences of "any" in ModalHalfScreen
=> feat(fscomponents): Replace all occurrences of "any" in ModalHalfScreen

packages/fscomponents/src/components/UpdateNameOrEmail.tsx
Replace all occurrences of "any" in LoginFormFK component
=> feat(fscomponents): Replace all occurrences of "any" in LoginFormFK component

packages/fscomponents/src/lib/applyDefaults.tsx
Replace all occurrences of "any" in applyDefaults
I can not replace some of any. It could break functionality
=> feat: Replace all occurrences of "any" in applyDefaults

packages/pirateship/src/components/PSAddressForm.tsx, packages/pirateship/src/lib/FieldOptionsTypes.tsx
Replace all occurrences of "any" in PSAddressForm
=> feat: Replace all occurrences of "any" in PSAddressForm

packages/fsweb/src/server.ssr.ts
Not sure how this was working at all before.
=> fix(fsweb): Fix path check

packages/fscomponents/src/components/RadioButtonLine.tsx, packages/fscomponents/src/components/__stories__/RadioButtonLine.story.tsx
This component represents a single line of a selection of radio buttons.
=> feat(fscomponents): Add RadioButtonLine component

packages/fscomponents/src/components/TooltipDisplay.tsx, packages/fscomponents/src/components/__stories__/TooltipDisplay.story.tsx
This is a component for the display of a tooltip.
=> feat(fscomponents): Add TooltipDisplay component

packages/fscomponents/src/components/Swatch.tsx, packages/fscomponents/src/components/Swatches.tsx, packages/fscomponents/src/components/__stories__/Swatches.story.tsx, packages/fscomponents/src/styles/Swatches.ts
Updated for new version of OptionValue, which has swatch data in it. Deprecated color and image, which are now redundant. Also added event override for clicking the plus.
=> feat(fscomponents): Updates to Swatches

packages/fsapp/src/components/screenWrapper.tsx, packages/fsapp/src/lib/helpers.ts, packages/fsapp/src/lib/nav-wrapper.ts, packages/fsapp/src/lib/nav-wrapper.web.tsx, packages/fsapp/src/lib/push-route.ts, packages/fsapp/src/types/index.ts
Allows opening a screen in the app by url and getting the web url of the current screen.
=> feat(fsapp): Url handling for native

packages/fsapp/src/components/screenWrapper.tsx, packages/fsapp/src/lib/helpers.ts, packages/fsapp/src/lib/nav-wrapper.ts, packages/fsapp/src/lib/nav-wrapper.web.tsx, packages/fsapp/src/lib/push-route.ts, packages/fsapp/src/types/index.ts
Reverts brandingbrand/flagship#1817
=> chore: revert "feat(fsapp): Url handling for native"

packages/fsapp/src/components/DrawerRouter.web.tsx, packages/fsapp/src/lib/nav-wrapper.web.tsx, packages/fsapp/src/lib/push-route.ts, packages/fsapp/src/types/index.ts
allow for routerConfig to be registered with app and register web routes based on those.
=> feat: register custom routes when using routerConfig

packages/fsapp/package.json, packages/fsapp/src/lib/app-router.ts, packages/fsapp/src/types/index.ts
In my original PR there were a lot of `any`s so I added some typing and also moved some types from the flagship-demo repo in here where it should be.
=> fix(fsapp): fix typing for app router

packages/fscommerce/src/Commerce/CommerceTypes.ts, packages/fscommerce/src/Commerce/interfaces/ProductCatalogDataSource.ts, packages/fscommerce/src/Commerce/types/Product.ts, packages/fscommerce/src/Commerce/types/ProductPromotion.ts
- implemented the request to get details for product promotions
Test together with PR:
https://github.com/brandingbrand/submarine/pull/314
=> feat(fscommerce): product promotions

packages/fscomponents/src/components/serializable/SerializableButton.tsx, packages/fscomponents/src/components/serializable/SerializableImage.tsx, packages/fscomponents/src/components/serializable/SerializableImagePlaceholder.tsx, packages/fscomponents/src/components/serializable/SerializableText.tsx, packages/fscomponents/src/components/serializable/SerializableTooltip.tsx, packages/fscomponents/src/components/serializable/SerializableView.tsx, packages/fscomponents/src/components/serializable/VideoBlock.tsx, packages/fscomponents/src/components/serializable/VideoBlock.web.tsx, packages/fscomponents/src/components/serializable/index.ts, packages/fscomponents/src/index.ts, packages/fscomponents/src/lib/style.ts
This includes fixes required for the the Noah's Ark Serializable Component Migration
=> fix(fscomponents): serializable component fixes

packages/fsapp/src/beta-app/router/history/history.ts, packages/fsapp/src/beta-app/router/history/history.web.ts, packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/utils.ts
This fixes external route linking conflicts that would cause sub routes to be unexpectedly overwritten.
=> fix(fsapp): linking conflicts

packages/fsapp/src/beta-app/modal/make-modal.ts, packages/fsapp/src/beta-app/modal/make-modal.web.ts, packages/fsapp/src/beta-app/modal/modal.context.tsx, packages/fsapp/src/beta-app/modal/types.ts
will default to hiding the nav bar for modals
=> feat: allow custom nav bar styles on makeModal

packages/fsapp/src/beta-app/router/router.tsx, packages/fsapp/src/beta-app/router/utils.ts
@bweissbart @wSedlacek 
- remove preceding slash from external route after removing tab path
- prevent route id from being registered twice
=> fix: fix external route paths

packages/fscomponents/src/components/serializable/SerializableCategoryLine.tsx
This adds a Serializable Category Line that can link to other pages with FSAppBeta
=> feat(fscomponents): Serializable Cateogry Line

packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/history/utils.native.tsx, packages/fsapp/src/beta-app/router/types.ts
@wSedlacek @bweissbart 
`statusBarStyle` is something we're going to start passing into to RouteCollections
=> fix: apply navbar styles to RouteCollections

packages/fscomponents/src/components/index.ts, packages/fscomponents/src/components/serializable/v2/SerializableAccordion.tsx, packages/fscomponents/src/components/serializable/v2/SerializableImage.tsx, packages/fscomponents/src/components/serializable/v2/SerializableProgressBar.tsx, packages/fscomponents/src/components/serializable/v2/SerializableText.tsx, packages/fscomponents/src/components/serializable/v2/SerializableToggleButton.tsx, packages/fscomponents/src/components/serializable/v2/SerializableTooltip.tsx, packages/fscomponents/src/components/serializable/v2/SerializableVideoBlock.tsx, packages/fscomponents/src/components/serializable/v2/SerializableVideoBlock.types.ts, packages/fscomponents/src/components/serializable/v2/SerializableVideoBlock.web.tsx, packages/fscomponents/src/components/serializable/v2/SerializableView.tsx, packages/fscomponents/src/components/serializable/v2/index.ts
This formalizes Serializable V2﻿
=> feat(fscomponents): serializable v2 component

packages/fscomponents/src/components/serializable/v2/SerializableImage.tsx, packages/fscomponents/src/components/serializable/v2/SerializableReviewIndicator.tsx, packages/fscomponents/src/components/serializable/v2/index.ts
=> chore(fscomponents): update v2 with pending changes

packages/flagship/src/commands/init.ts, packages/fsweb/polyfills/document.js, packages/fsweb/polyfills/navigator.js, packages/fsweb/polyfills/window.js, packages/fsweb/webpack.config.js, packages/fsweb/webpack.ssr.js
- updated polyfills to avoid building and rendering issues with SSR
- updated webpack config to skip minimization in dev mode
- updated flagship command init to allow development with yarn link
=> fix(fsweb): update polyfills

packages/fsengagement/src/__stories__/FeaturedTopCard.story.tsx, packages/fsengagement/src/inboxblocks/FeaturedTopCard.tsx, packages/fsengagement/src/inboxblocks/TitleWithLink.tsx, packages/fsengagement/src/inboxblocks/index.tsx
- fix context usage in "TitleWithLink" component
- update "FeaturedTopCard" component to be FC to use new context
=> fix(fsengagement): fix for context in TitleWithLink

packages/fscomponents/src/components/Grid.tsx
Ticket: https://brandingbrand.atlassian.net/browse/FS-2639
This refactors the grid component to be a functional component
This refactors the grid component to use the same prop names as FlatList
This adds in a `numColumns` `auto` which will set the number of columns based on how many of a minimum sizes can fit
This looks for specified widths in the styles to use for the initial values as a performance optimization, when the width is not
known a blank single render will need to occur to measure the layout size before column calculations can occur.
This uses `onContentSizeChange` rather than `onLayout` so that when the size changes, like on Web, it will be accurately updated.
BREAKING CHANGE: Deprecated several props in `<Grid />`
=> feat(fscomponents): FS-2639 - Builder | Allowing setting Container grid columns per breakpoint

packages/fscomponents/src/components/Grid.tsx, packages/fscomponents/src/components/MultiCarousel/CarouselController.ts, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx, packages/fscomponents/src/components/MultiCarousel/MultiCarouselProps.ts, packages/fscomponents/src/components/MultiCarousel/index.ts, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.tsx, packages/fscomponents/src/components/ZoomCarousel/ZoomCarousel.web.tsx, packages/fscomponents/src/lib/helpers.ts, packages/pirateship/src/components/PSProductCarousel.tsx
This updates the `MultiCarousel` component to be a functional component
This updates the scrolling behavior of the `MultiCarousel` component so it is more natural on all platforms (especially web)
This adds a new porp `itemWidth` which will allow setting a specific width for items in the carousel to be.
=> feat(fscomponents): FS-2640 - Builder | Allowing setting number of items to show per breakpoint

packages/fsweb/.babelrc, packages/fsweb/babel.config.js, packages/fsweb/webpack.config.js
This fixes the warning message that commonly shows up when building web projects
=> fix(fsweb): babel warnings about private properties in object

packages/fscomponents/src/components/Grid.tsx
This updates the Grid component to rerender when it's render has changed
=> fix(fscomponents): rerender when render changes

packages/fsapp/src/beta-app/app/app.ts, packages/fsapp/src/beta-app/app/types.ts
This allows apps to use custom logic for deep link initialization
=> feat(fsapp): get initial url

packages/fsapp/src/beta-app/app/app.ts, packages/fsapp/src/beta-app/router/history/history.ts, packages/fsapp/src/beta-app/router/history/queue.decorator.ts, packages/fsapp/src/beta-app/router/history/utils.base.ts, packages/fsapp/src/beta-app/router/history/utils.native.tsx, packages/fsapp/src/beta-app/router/router.web.tsx, packages/fsapp/src/beta-app/router/types.ts, packages/fsapp/src/beta-app/router/utils.ts
This allows guarding activations
This allows using params in redirects
=> feat(fsapp): complex activations

package.json, yarn.lock
=> chore: update prism dependency

.travis.yml
This should fix the build issues seen in #2278
=> chore: fix travis timeouts for ios compile

packages/fscomponents/src/components/MultiCarousel/MultiCarousel.web.tsx
* Fixes an issue that prevented a user from swiping successfully in Safari 14
=> fix(fscomponents): Fix Safari Scroll Issue

.storybook/main.js, package.json, yarn.lock
This updates the storybook dependencies to their latest versions, fixes the syntax to register addons, and addresses outdated packages that were introduced by or not fixed within the new versions.
=> chore: update storybook dependencies 

packages/fscomponents/package.json, yarn.lock
Removes the unused react-native-elements dependency.
Closes #2155
=> chore(fscomponents): remove unused react-native-elements

packages/fsweb/package.json, yarn.lock
Reverts brandingbrand/flagship#2315
=> Revert "chore: bump webpack-cli from 3.3.12 to 4.9.1"

packages/fscommerce/src/Commerce/CommerceTypes.ts, packages/fscommerce/src/Commerce/types/CurrencyValue.ts
Tciket:
https://brandingbrand.atlassian.net/browse/FS-3207
=> fix: exported currency value from it's own type file instead of index

packages/fslinker/__tests__/class.spec.ts, packages/fslinker/__tests__/global.spec.ts, packages/fslinker/__tests__/value.spec.ts, packages/fslinker/src/cache/cache.ts, packages/fslinker/src/cache/global-cache.ts, packages/fslinker/src/injectable.ts, packages/fslinker/src/injector.ts, packages/fslinker/src/providers.ts
Reverts brandingbrand/flagship#2197
Causes issue with existing bundles
=> Revert "refactor(fslinker): use symbols in fslinker"

packages/fsengagement/src/inboxblocks/ShopIngredientsBlock.tsx
All class components need to be fixed to utilize the new context, the `ShopIngredients` component was missed.
=> fix(fsengagement): no-ticket - fix ShopIngredients context

packages/fscomponents/src/components/ChangePasswordComponent.tsx, packages/fscomponents/src/components/__stories__/ChangePassword.story.tsx
Replace all any fscomponents change password
=> Replace all any fscomponents change password

packages/flagship/ios/FLAGSHIP-Bridging-Header.h, packages/flagship/ios/FLAGSHIP.xcodeproj/project.pbxproj, packages/flagship/ios/Podfile, packages/flagship/ios/fix.swift
Reverts brandingbrand/flagship#2189
This includes a breaking change that needs to wait for FS 12
=> Revert "feat(flagship): stripe lib support"

packages/flagship/android/app/src/main/AndroidManifest.xml, packages/flagship/android/build.gradle, packages/flagship/src/lib/android.ts
[FCR-3188](https://brandingbrand.atlassian.net/browse/FCR-3188) -Implement Android 31 in Flagship v10
- Updating AndroidManifest.xml to include `android:exported` tags
- Updating gradle wrapper `targetSdkVersion` and `compileSdkVersion` to API 31
=> FS Android 12 support

packages/core/src/types.ts
[FCR-3511](https://brandingbrand.atlassian.net/browse/FCR-3511)
[FCR-3510](https://brandingbrand.atlassian.net/browse/FCR-3510)
- Typed env config
=> feat(fs12): typed env config

README.md
=> chore: adding readme

docs/src/pages/en/introduction.md
In this PR, I address the following within `src/pages/en/introduction.md`
- Typos
- Summarize key points to make for quicker reading
- (nit) Remove superfluous details
=> chore: Edit Introduction.md

.github/workflows/pr-test.yml
The purpose of this workflow is to build and run our tests when someone creates a PR. This will allow developers to catch issues sooner and proactively fix their PRs before they are reviewed.
=> feat(repo): creating pr test action

packages/core/assets/template/android/app/src/main/res/values/colors.xml, packages/plugin-leanplum/src/index.ts
This does bring up some pain points in not being able to test full implementation of plugins/libraries that require some kind of higher level configuration i.e. firebase.
This does bring up some pain points about having a raw template for testing an ejs template for configuration. We may think about how to merge the 2 ideas. Something for a later time to talk about.
=> fix(fs12): plugin-leanplum imports

docs/src/pages/en/faq.md, docs/src/pages/en/introduction.md, docs/src/pages/en/roadmap.md, docs/src/pages/en/usage/integration.mdx, docs/src/pages/en/usage/troubleshooting.md
- Consistent naming for iOS and Android.
- Resolved typos
- Update headers to match the names in the list of roadmap items.
- Moved the summary of the roadmap from the end of the document to the top of the document to improve readability.
- Fix typos
- Update the bug report section to use the same language used in the roadmap document
- Fix typos
- Improve readability
- This document remains empty
=> FCR-4419 - task(docs): Review and Revise Documentation

packages/cli/README.md, packages/cli/package.json
=> chore: add README for code-cli package

packages/plugin-app-icon/README.md, packages/plugin-app-icon/package.json
=> chore: add README for code-plugin-app-icon package

packages/plugin-asset/README.md, packages/plugin-asset/package.json
=> chore: add README for code-plugin-asset package

packages/plugin-fbsdk-next/README.md, packages/plugin-fbsdk-next/package.json
=> chore: add README for code-plugin-fbsdk-next package

packages/plugin-firebase-analytics/README.md, packages/plugin-firebase-analytics/package.json
=> chore: add README for code-plugin-firebase-analytics package

packages/plugin-firebase-app/README.md, packages/plugin-firebase-app/package.json
=> chore: add README for code-plugin-firebase-app package

packages/plugin-google-signin/README.md, packages/plugin-google-signin/package.json
=> chore: add README for code-plugin-google-signin package

packages/plugin-leanplum/README.md, packages/plugin-leanplum/package.json
=> chore: add README for code-plugin-leanplum package

packages/plugin-native-navigation/README.md, packages/plugin-native-navigation/package.json
=> chore: add README for code-plugin-native-navigation package

packages/plugin-splash-screen/README.md, packages/plugin-splash-screen/package.json
=> chore: add README for code-plugin-splash-screen package

packages/plugin-target-extension/README.md, packages/plugin-target-extension/package.json
=> chore: add README for code-plugin-target-extension package

packages/plugin-permissions/README.md, packages/plugin-permissions/package.json
=> chore: add README for code-plugin-permissions package

.github/workflows/deploy-docs.yml
move doc deploy branch to target main
=> chore: move doc deploy to target main branch

.changeset/config.json, docs/src/pages/en/packages/plugins/leanplum/v1.0.1.mdx, packages/plugin-leanplum/CHANGELOG.md, packages/plugin-leanplum/package.json
update docs for 1.0.1 patch for @brandingbrand/code-plugin-leanplum
update version to 1.0.1 in package.json
=> docs(leanplum): 1.0.1 version changelog and docs

docs/src/pages/en/packages/core/v12.0.1.mdx, packages/core/CHANGELOG.md, packages/core/package.json
@brandingbrand/code-core 12.0.1 docs and changelog
* run docs `yarn dev:docs`
* verify documentation text
=> docs(core): 12.0.1 docs and changelog

.github/workflows/pr-test.yml
update runner to ubuntu
add timeout
remove init step
After merge verify actions running on proper device with timeout
=> chore: simplify pr test

LICENSE.txt
add License.txt file back from previous versions
=> chore: add license

docs/src/pages/en/packages/plugins/fastlane/v2.0.0.mdx, docs/src/styles/global.css
Update documentation for fastlane plugin v2.0.0. Adds additional context to CI/CD expectations.
=> feat(fastlane): fastlane plugin v2.0.0 docs

apps/docs/src/content/docs/guides/build.mdx, packages/cli-kit/src/schemas/build-config.ts, packages/cli/__tests__/build-gradle.ts, packages/cli/src/transformers/android/app-build-gradle.ts, packages/cli/src/transformers/android/build-gradle.ts, packages/cli/src/transformers/android/gemfile.ts, packages/cli/src/transformers/ios/gemfile.ts, packages/cli/src/transformers/ios/podfile.ts
Add ability to add specific `kotlinVersion`. Default value is `1.7.10` - this is guaranteed for sdk 33. Update padding for string based array transformations.
=> feat(code): update padding and kotlinVersion

apps/docs/src/content/docs/guides/build.mdx, packages/cli-kit/src/schemas/build-config.ts, packages/cli/__tests__/android-maniest-xml.ts, packages/cli/__tests__/info-plist.ts, packages/cli/src/transformers/android/android-manifest-xml.ts, packages/cli/src/transformers/ios/info-plist.ts
Add option to set screen orientation via build config.
=> feat(code): add screen orientation config

packages/plugin-target-extension/src/index.ts
Target Extension should be it's own directory a part of the main xcode project.
Used `npm pack` and tested in project.
=> feat(code): update target-ext location

packages/cli-kit/src/@types/android-manifest-xml.ts, packages/plugin-splash-screen/__tests__/generated.ts, packages/plugin-splash-screen/src/legacy.ts
Add `Resources` group safely and to main project. Add attribute to `AndroidManifest.xml` type.
=> chore(code): add resources and manifest export

.changeset/fast-flowers-travel.md, packages/plugin-fastlane/__tests__/index.ts, packages/plugin-fastlane/template/android/fastlane/Fastfile
Update Android Fastfile to fix not incrementing build numbers for the bundle lane.
`yarn test`
=> fix(fastlane): add increment build to bundle lane

.changeset/spicy-kiwis-perform.md, packages/cli/__tests__/project-pbxproj.ts, packages/cli/src/transformers/ios/project-pbxproj.ts, packages/cli/template/extras/ios/app/PrivacyInfo.xcprivacy
Add `PrivacyInfo.xcprivacy` inline with Apple's new Privacy requirements: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc. This was added to `react-native` v0.74.0: https://github.com/facebook/react-native/commit/2d84d835342d58bd28b2233f18691846de6933c9.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5152)
`yarn test` and run example app.
=> feat(code): ENG-5152 add PrivacyInfo.xcprivacy privacy manifest

.changeset/tricky-elephants-leave.md, packages/plugin-firebase-analytics/package.json, packages/plugin-firebase-app/package.json
Update `firebase` plugin to support privacy manifest.
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5151)
`yarn test`
=> feat(firebase): ENG-5151 update firebase support for privacy manifest

.changeset/big-penguins-tease.md, .changeset/fresh-years-agree.md, .changeset/lemon-news-shave.md, .changeset/long-rabbits-pull.md, .changeset/pretty-yaks-chew.md, .changeset/tricky-elephants-leave.md, docs/src/pages/en/packages/core/v12.1.0.mdx, docs/src/pages/en/packages/plugins/fbsdk-next/v1.1.0.mdx, docs/src/pages/en/packages/plugins/firebase-analytics/v1.1.0.mdx, docs/src/pages/en/packages/plugins/firebase-app/v1.1.0.mdx, docs/src/pages/en/packages/plugins/google-signin/v1.1.0.mdx, docs/src/pages/en/packages/plugins/leanplum/v1.1.0.mdx, packages/core/CHANGELOG.md, packages/core/package.json, packages/plugin-fbsdk-next/CHANGELOG.md, packages/plugin-fbsdk-next/package.json, packages/plugin-firebase-analytics/CHANGELOG.md, packages/plugin-firebase-analytics/package.json, packages/plugin-firebase-app/CHANGELOG.md, packages/plugin-firebase-app/package.json, packages/plugin-google-signin/CHANGELOG.md, packages/plugin-google-signin/package.json, packages/plugin-leanplum/CHANGELOG.md, packages/plugin-leanplum/package.json
Bump versions and update documentation for PrivacyInfo.xcprivacy support.
=> chore(version): bump version support privacy manifest

.changeset/gorgeous-berries-compare.md, packages/cli-kit/src/@types/android-manifest-xml.ts
Expose `queries` attribute in Android Manifest: https://developer.android.com/guide/topics/manifest/queries-element.
1. `yarn test`
=> feat(cli-kit): expand AndroidManifest types

.changeset/seven-tools-relate.md, packages/cli/src/transformers/ios/info-plist.ts
Remove only `localhost` exception domain in release mode.
1. `yarn test`
=> fix(cli): remove only localhost exception domain in release

.gitignore, packages/plugin-native-navigation/__tests__/fixtures/node_modules/react-native-navigation/autolink/postlink.sh, packages/plugin-native-navigation/__tests__/fixtures/node_modules/react-native-navigation/autolink/postlink/path.js, packages/plugin-native-navigation/__tests__/fixtures/node_modules/react-native-navigation/autolink/postlink/postLinkAndroid.js, packages/plugin-native-navigation/__tests__/fixtures/node_modules/react-native-navigation/autolink/postlink/postLinkIOS.js, packages/plugin-native-navigation/__tests__/fixtures/node_modules/react-native-navigation/package.json, packages/plugin-native-navigation/__tests__/index.ts, packages/plugin-native-navigation/src/index.ts
Sync overridden kotlin version with react-native-navigation kotlin version.
1. `yarn test`
=> fix(plugin): react-native-navigation kotlin override

.changeset/small-toys-argue.md, apps/example/package.json, packages/plugin-permissions/CHANGELOG.md, packages/plugin-permissions/package.json
bump versions for release of @brandingbrand/code-plugin-permissions package
verify version bump
=> chore(plugin-permission): version bump for patch fix

.changeset/small-toys-argue.md, apps/example/package.json, packages/cli/package.json, packages/cli/src/actions/info.ts, packages/plugin-permissions/CHANGELOG.md, packages/plugin-permissions/__tests__/index.ts, packages/plugin-permissions/package.json, packages/plugin-permissions/src/index.ts, yarn.lock
merge develop into main with plugin-permissions release
=> chore: merge develop into main with plugin-permissions release

.changeset/long-pigs-bow.md, packages/cli/src/actions/info.ts
If update-check fails it will early exit the program. Wrap with try/catch and log error message.
- `yarn test`
- intentionally throw error in update check block
- `yarn flagship-code prebuild --build internal --env prod`
- Verify no early exit and error message
<details>
<summary>error</summary>
</details>
=> fix: update-check log error

.changeset/cuddly-comics-remember.md, .changeset/long-pigs-bow.md, apps/example/package.json, packages/cli/CHANGELOG.md, packages/cli/package.json
update version of @brandignbrand/code-cli library for release 
verify version bump
=> chore: version bump for @brandingbrand/code-cli patch

packages/cli-kit/README.md, packages/cli/README.md, packages/jest-config/README.md, packages/plugin-app-icon/README.md, packages/plugin-asset/README.md, packages/plugin-fastlane/README.md, packages/plugin-native-navigation/README.md, packages/plugin-permissions/README.md, packages/plugin-splash-screen/README.md, packages/plugin-target-extension/README.md
[Ticket](https://brandingbrand.atlassian.net/browse/ENG-5588)
README.md links to Flagship Code™ docs were incorrect.
- `yarn test`
=> docs: incorrect readme links

apps/docs/src/content/docs/guides/getting-started.mdx, apps/docs/src/content/docs/overview/objectives.md, apps/docs/src/content/docs/packages/cli-kit.mdx, apps/docs/src/content/docs/packages/cli.mdx
Update documentation to reflect react-native 0.72 + 0.73 support and enhancements.
- `yarn test`
=> docs: react-native 0.73 support + enhancements

.changeset/old-yaks-hug.md
=> fix: react-native 0.73 missing changesets

packages/cli/package.json, packages/core/assets/__template__/ios/Gemfile, packages/core/assets/template/ios/Gemfile, packages/core/src/executors/init/platform/cocoapods.ts, yarn.lock
* Pin Xcodeproj and Cocoapods to operable versions
[ENG-5790](https://brandingbrand.atlassian.net/browse/ENG-5790)
[ENG-5790]: https://brandingbrand.atlassian.net/browse/ENG-5790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: pin xcodeproj and cocoapods to operable versions

packages/cli/CHANGELOG.md, packages/cli/package.json
update patch version to setup for release to fix related to xcodeproj release
https://brandingbrand.atlassian.net/browse/ENG-5792
https://brandingbrand.atlassian.net/browse/ENG-5788
verify version bump
=> chore(cli): version patch 12.0.1

apps/example/package.json, packages/cli/CHANGELOG.md, packages/cli/package.json
bump version for release of patch of cli
https://brandingbrand.atlassian.net/browse/ENG-5794
https://brandingbrand.atlassian.net/browse/ENG-5788
verify version update
=> chore(cli): patch version 13.1.1

packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/package.json
bump version of code-plugin-fastlane package
add changelog describing changes
* verify version and change log wording
=> chore(fastlane): bump version and generate changelog

packages/jest-config/CHANGELOG.md, packages/jest-config/package.json
update version to publish for code-cli 13.1.0 updates
* verify version
* verify changelog
* verify peer dependencies
=> chore(jest-config): version bump for code-cli version 13.1.0 support

apps/docs/package.json, yarn.lock
Bump astro to fix vulnerability.
NOTICKET
- `yarn test`
- run docs
=> feat(deps): bump astro

package.json, packages/eslint-config/package.json, turbo.json, yarn.lock
=> chore(deps): turbo v2

.changeset/itchy-readers-cover.md, apps/docs/src/content/docs/packages/plugin-fastlane.mdx, packages/plugin-fastlane/__tests__/index.ts, packages/plugin-fastlane/src/types.ts, packages/plugin-fastlane/template/android/fastlane/Fastfile, packages/plugin-fastlane/template/ios/fastlane/Fastfile
cherry pick changes from PR https://github.com/brandingbrand/flagship/pull/2798 to v13 branch
* was a clean cherry pick so can run smoke test from PR https://github.com/brandingbrand/flagship/pull/2798
Copied Steps For Reference:
* the easiest way might to do a npm pack of the package then install in an existing app
* run init and view fast lane files
* run fastlane increment_build_firebase and verify output
* modify build config to some different options and init again
* view fast files and run fastlane increment_build_firebase and verify output
=> feat(plugin-fastlane): add option to reset build numbers in firebase inc build

.changeset/itchy-readers-cover.md, packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/package.json
bump version to prep release of plugin fastlane
verify version bump
=> chore(plugin-fastlane): bump version to 4.1.0 for release

.changeset/itchy-readers-cover.md, packages/plugin-fastlane/CHANGELOG.md, packages/plugin-fastlane/package.json
update feature version plugin fastlane to publish to NPM as we want this feature on v13 peer dependency as well as the latest version
verify version
=> chore(plugin-fastlane): bump version to 3.2.0 for release

apps/example/package.json, packages/cli/CHANGELOG.md, packages/cli/package.json, yarn.lock
patch version bump of code-cli package to prep release
* verify version bumps
=> chore: version patch bump of code-cli package

packages/plugin-transform-template/src/transforms/0.72/android/app-build-gradle.ts
* Fix release signing by dynamic linking to the configured keystore file, if it exists.
* Improve error checking to ensure keystore and alias are configured correctly
[ENG-6196](https://brandingbrand.atlassian.net/browse/ENG-6196)
1. in example app, force resolution of "@brandingbrand/code-plugin-transform-template" to local version
2. In `coderc/build/internal.build.ts`, define a `signing` config for android, and place your keystore file 
3. run `yarn install && yarn run prebuild`
4. Open `android/app/build.gradle`, and confirm release signing config points to configured keystore file, instead of `release.keystore`
5. `cd` your CLI to `android`
6. run `bundle install`
8. Load your `KEY_PASSWORD` and `STORE_PASSWORD` envvars into your CLI …
=> fix(plugin-transform-template): Link to configured release keystore file

packages/preset-react-native/CHANGELOG.md, packages/preset-react-native/package.json, yarn.lock
Update preset package to reflect necessary update for `code-plugin-transform-template`
=> chore: bump preset dependency versions
